'use client';

import Link from 'next/link';

import { useEffect, useState, useRef } from 'react';
import { supabase } from '@/lib/supabase/client';
import { Eye, Radio } from 'lucide-react';

type LiveSession = {
    id: string;
    title: string;
    host_id: string;
    viewer_count: number;
    started_at: string;
    product_ids?: string[];
    profiles?: { full_name?: string; nickname?: string; avatar_url?: string; store_logo_url?: string } | null;
    thumbnail_url?: string; // first product image
};

export function LiveCarousel() {
    const [sessions, setSessions] = useState<LiveSession[]>([]);
    const [loaded, setLoaded] = useState(false);
    const intervalRef = useRef<NodeJS.Timeout | null>(null);

    useEffect(() => {
        const fetchSessions = async () => {
            try {
                const res = await fetch('/api/live?status=live');
                const d = await res.json();
                const liveSessions: LiveSession[] = d.sessions || [];

                // For each session, try to load stream thumbnail + fallback to product image
                const thumbChecks = liveSessions.map(async (s) => {
                    // 1. Try live stream thumbnail (generated by ffmpeg on server)
                    const thumbUrl = `https://livekit.gopocket.com.mx/thumbs/${s.id}.jpg?t=${Math.floor(Date.now() / 30000)}`;
                    try {
                        const r = await fetch(thumbUrl, { method: 'HEAD' });
                        if (r.ok) { s.thumbnail_url = thumbUrl; return; }
                    } catch { }

                    // 2. Fallback: first product image
                    if (s.product_ids?.length) {
                        const { data: products } = await supabase
                            .from('listings')
                            .select('id, images')
                            .in('id', s.product_ids.slice(0, 1));
                        if (products?.[0]?.images?.[0]) {
                            s.thumbnail_url = products[0].images[0];
                        }
                    }
                });

                await Promise.all(thumbChecks);

                setSessions(liveSessions);
                setLoaded(true);
            } catch {
                setLoaded(true);
            }
        };

        fetchSessions();
        intervalRef.current = setInterval(fetchSessions, 10000);

        const channel = supabase
            .channel('live-carousel-sync')
            .on(
                'postgres_changes',
                { event: '*', schema: 'public', table: 'live_sessions' },
                () => { fetchSessions(); }
            )
            .subscribe();

        return () => {
            if (intervalRef.current) clearInterval(intervalRef.current);
            supabase.removeChannel(channel);
        };
    }, []);

    if (!loaded || sessions.length === 0) return null;

    return (
        <section className="w-full py-6 px-4">
            <div className="mx-auto max-w-6xl">
                {/* Header */}
                <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center gap-2.5">
                        <div className="relative flex items-center justify-center w-8 h-8">
                            <div className="absolute w-8 h-8 rounded-full bg-red-500 opacity-30 animate-ping" />
                            <div className="relative w-4 h-4 rounded-full bg-red-600" />
                        </div>
                        <h2 className="text-lg font-extrabold text-gray-900">En Vivo Ahora</h2>
                        <span className="bg-red-600 text-white text-[10px] font-black px-2 py-0.5 rounded-full tracking-wider">
                            {sessions.length} LIVE{sessions.length !== 1 ? 'S' : ''}
                        </span>
                    </div>
                    <Link href="/live" className="text-sm font-semibold text-red-600 hover:text-red-700 transition-colors flex items-center gap-1">
                        Ver todos →
                    </Link>
                </div>

                {/* Cards scroll */}
                <div className="flex gap-4 overflow-x-auto pb-2 scrollbar-none snap-x snap-mandatory">
                    {sessions.map((s) => {
                        const hostName = s.profiles?.nickname || s.profiles?.full_name || 'Vendedor';
                        const avatar = s.profiles?.store_logo_url || s.profiles?.avatar_url;
                        const elapsed = Math.floor((Date.now() - new Date(s.started_at).getTime()) / 60000);
                        const elapsedStr = elapsed < 60 ? `${elapsed}m` : `${Math.floor(elapsed / 60)}h ${elapsed % 60}m`;
                        const hasThumbnail = !!s.thumbnail_url;

                        return (
                            <Link
                                key={s.id}
                                href={`/live/${s.id}`}
                                className="group relative flex-shrink-0 w-72 h-80 rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl hover:scale-[1.03] transition-all duration-300 snap-start"
                            >
                                {/* Background — product thumbnail or animated gradient */}
                                {hasThumbnail ? (
                                    <img
                                        src={s.thumbnail_url}
                                        alt={s.title}
                                        className="absolute inset-0 w-full h-full object-cover"
                                    />
                                ) : (
                                    <div className="absolute inset-0 bg-gradient-to-br from-red-900 via-gray-900 to-black" />
                                )}

                                {/* Dark gradient overlay for readability */}
                                <div className="absolute inset-0 bg-gradient-to-t from-black via-black/50 to-transparent" />

                                {/* Animated border glow */}
                                <div className="absolute inset-0 rounded-2xl ring-2 ring-red-500/50 group-hover:ring-red-400/80 transition-all" />

                                {/* ─── TOP BAR ─── */}
                                <div className="absolute top-0 left-0 right-0 flex items-center justify-between p-3 z-10">
                                    {/* Live badge */}
                                    <div className="flex items-center gap-1.5 bg-red-600 px-2.5 py-1 rounded-full shadow-lg shadow-red-600/40">
                                        <Radio className="w-3 h-3 text-white animate-pulse" />
                                        <span className="text-[10px] font-black text-white tracking-wider">EN VIVO</span>
                                    </div>

                                    {/* Viewer count */}
                                    <div className="flex items-center gap-1.5 bg-black/60 backdrop-blur-sm px-2.5 py-1 rounded-full">
                                        <Eye className="w-3 h-3 text-white/80" />
                                        <span className="text-[11px] font-bold text-white tabular-nums">{s.viewer_count || 0}</span>
                                    </div>
                                </div>

                                {/* ─── BOTTOM CONTENT ─── */}
                                <div className="absolute bottom-0 left-0 right-0 p-4 z-10">
                                    {/* Host info */}
                                    <div className="flex items-center gap-2.5 mb-2">
                                        <div className="w-9 h-9 rounded-full overflow-hidden border-2 border-white/30 shadow-lg flex-shrink-0 bg-gray-800">
                                            {avatar ? (
                                                <img src={avatar} alt={hostName} className="w-full h-full object-cover" />
                                            ) : (
                                                <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-red-500 to-orange-500 text-white text-sm font-bold">
                                                    {hostName.charAt(0).toUpperCase()}
                                                </div>
                                            )}
                                        </div>
                                        <div className="min-w-0">
                                            <p className="text-white text-xs font-semibold truncate">{hostName}</p>
                                            <p className="text-white/50 text-[10px]">⏱ {elapsedStr}</p>
                                        </div>
                                    </div>

                                    {/* Title */}
                                    <p className="text-white font-bold text-sm leading-tight line-clamp-2 mb-3">{s.title}</p>

                                    {/* Watch button */}
                                    <div className="flex items-center gap-2 bg-red-600 group-hover:bg-red-500 transition-colors rounded-xl px-4 py-2 w-fit shadow-lg shadow-red-600/30">
                                        <div className="w-2 h-2 rounded-full bg-white animate-pulse" />
                                        <span className="text-white text-xs font-bold">Ver live</span>
                                    </div>
                                </div>
                            </Link>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}
