import { normalize } from './utils';

export const GENDER_KEYWORDS: Record<string, string> = {
  'mujer': 'Mujer',
  'dama': 'Mujer',
  'senora': 'Mujer',
  'hombre': 'Hombre',
  'caballero': 'Hombre',
  'nino': 'Niños, Niñas y Bebés',
  'nina': 'Niños, Niñas y Bebés',
  'infantil': 'Niños, Niñas y Bebés',
  'bebe': 'Niños, Niñas y Bebés',
};

// Map keywords to semantic category concepts
// Format: "Category:SubCategory:SubSubCategory" or "Category:SubCategory"
export const KEYWORD_CONCEPTS: Record<string, string> = {
  // --- MODA ROPA Y ACCESORIOS ---
  // Accesorios de Moda
  'reloj': 'Accesorios de Moda:Relojes:Analogicos',
  'smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'joyeria': 'Accesorios de Moda:Joyería:Fantasia',
  'collar': 'Accesorios de Moda:Joyería:Collares',
  'dije': 'Accesorios de Moda:Joyería:Collares',
  'arete': 'Accesorios de Moda:Joyería:Aretes',
  'broquel': 'Accesorios de Moda:Joyería:Aretes',
  'pulsera': 'Accesorios de Moda:Joyería:Pulseras',
  'brazalete': 'Accesorios de Moda:Joyería:Pulseras',
  'anillo': 'Accesorios de Moda:Joyería:Anillos',
  'lentes': 'Accesorios de Moda:Lentes:Sol',
  'gafas': 'Accesorios de Moda:Lentes:Sol',
  'lentes sol': 'Accesorios de Moda:Lentes:Sol',
  'gafas sol': 'Accesorios de Moda:Lentes:Sol',
  'lentes oftalmicos': 'Accesorios de Moda:Lentes:Oftalmicos',
  'armazon': 'Accesorios de Moda:Lentes:Oftalmicos',
  'equipaje': 'Accesorios de Moda:Equipaje:Maletas',
  'maleta': 'Accesorios de Moda:Equipaje:Maletas',
  'mochila': 'Accesorios de Moda:Equipaje:Mochilas',
  'backpack': 'Accesorios de Moda:Equipaje:Mochilas',
  'bolsa viaje': 'Accesorios de Moda:Equipaje:Bolsas Viaje',
  'cangurera': 'Accesorios de Moda:Equipaje:Cangureras',
  'cinturon': 'Accesorios de Moda:Varios:Cinturones',
  'gorra': 'Accesorios de Moda:Varios:Gorras',
  'sombrero': 'Accesorios de Moda:Varios:Gorras',
  'bufanda': 'Accesorios de Moda:Varios:Bufandas',
  'panuelo': 'Accesorios de Moda:Varios:Bufandas',
  'paraguas': 'Accesorios de Moda:Varios:Paraguas',

  // Mujer (Root Override handled in logic)
  'vestido': 'Mujer:Ropa:Vestidos',
  'blusa': 'Mujer:Ropa:Blusas y Tops',
  'top': 'Mujer:Ropa:Blusas y Tops',
  'falda': 'Mujer:Ropa:Faldas y Shorts',
  'short mujer': 'Mujer:Ropa:Faldas y Shorts',
  'abrigo mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'chamarra mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'sueter mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'sudadera mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'lenceria': 'Mujer:Ropa:Lencería y Ropa Interior',
  'calzon': 'Mujer:Ropa:Lencería y Ropa Interior',
  'brasier': 'Mujer:Ropa:Lencería y Ropa Interior',
  'traje bano mujer': 'Mujer:Ropa:Trajes de Baño',
  'bikini': 'Mujer:Ropa:Trajes de Baño',
  'ropa deportiva mujer': 'Mujer:Ropa:Ropa Deportiva',
  'leggins': 'Mujer:Ropa:Ropa Deportiva',
  'overol': 'Mujer:Ropa:Overoles y Jumpers',
  'jumper': 'Mujer:Ropa:Overoles y Jumpers',
  'pijama mujer': 'Mujer:Ropa:Pijamas',
  'bolsa mano': 'Mujer:Bolsas:Bolsas',
  'tote': 'Mujer:Bolsas:Bolsas',
  'crossbody': 'Mujer:Bolsas:Bolsas',
  'clutch': 'Mujer:Bolsas:Clutches',
  'cartera mujer': 'Mujer:Bolsas:Carteras',
  'tenis mujer': 'Mujer:Calzado:Tenis',
  'tenis': 'Mujer:Calzado:Tenis',
  'bota mujer': 'Mujer:Calzado:Botas',
  'botin mujer': 'Mujer:Calzado:Botas',
  'sandalia mujer': 'Mujer:Calzado:Sandalias',
  'zapatilla': 'Mujer:Calzado:Tacones',
  'tacon': 'Mujer:Calzado:Tacones',
  'flats': 'Mujer:Calzado:Flats',
  'balerina': 'Mujer:Calzado:Flats',

  // Hombre
  'playera': 'Hombre:Ropa:Playeras y Polos',
  'polo': 'Hombre:Ropa:Playeras y Polos',
  'camisa': 'Hombre:Ropa:Camisas',
  'pantalon hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'jeans hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'short hombre': 'Hombre:Ropa:Shorts y Bermudas',
  'bermuda': 'Hombre:Ropa:Shorts y Bermudas',
  'sudadera hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'sueter hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'chamarra hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'abrigo hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'chaleco hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'traje hombre': 'Hombre:Ropa:Trajes y Sacos',
  'saco': 'Hombre:Ropa:Trajes y Sacos',
  'boxer': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calzoncillo': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calcetin': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'traje bano hombre': 'Hombre:Ropa:Trajes de Baño',
  'ropa deportiva hombre': 'Hombre:Ropa:Ropa Deportiva',
  'tenis hombre': 'Hombre:Calzado:Tenis',
  'zapato vestir': 'Hombre:Calzado:Zapatos Vestir',
  'bota hombre': 'Hombre:Calzado:Botas',
  'sandalia hombre': 'Hombre:Calzado:Sandalias',
  'chancla': 'Hombre:Calzado:Sandalias',

  // Niños/Bebes
  'ropa bebe': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'pañalero': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'zapato bebe': 'Niños, Niñas y Bebés:Bebés:Zapatos Bebé',
  'babero': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'vestido nina': 'Niños, Niñas y Bebés:Niñas:Vestidos',
  'conjunto nina': 'Niños, Niñas y Bebés:Niñas:Conjuntos',
  'playera nina': 'Niños, Niñas y Bebés:Niñas:Playeras',
  'falda nina': 'Niños, Niñas y Bebés:Niñas:Faldas',
  'zapato nina': 'Niños, Niñas y Bebés:Niñas:Zapatos Niña',
  'conjunto nino': 'Niños, Niñas y Bebés:Niños:Conjuntos',
  'playera nino': 'Niños, Niñas y Bebés:Niños:Playeras',
  'pantalon nino': 'Niños, Niñas y Bebés:Niños:Pantalones',
  'sudadera nino': 'Niños, Niñas y Bebés:Niños:Sudaderas',
  'zapato nino': 'Niños, Niñas y Bebés:Niños:Zapatos Niño',

  // Ropa Especializada
  'disfraz': 'Ropa Especializada / Otros:Especializada:Disfraces y Cosplay',
  'cosplay': 'Ropa Especializada / Otros:Especializada:Disfraces y Cosplay',
  'bata medico': 'Ropa Especializada / Otros:Especializada:Ropa de Trabajo Industrial',
  'uniforme': 'Ropa Especializada / Otros:Especializada:Ropa de Trabajo Industrial',
  'maternidad': 'Ropa Especializada / Otros:Especializada:Ropa de Maternidad',
  'embarazada': 'Ropa Especializada / Otros:Especializada:Ropa de Maternidad',
  'talla extra': 'Ropa Especializada / Otros:Especializada:Tallas Extra (Plus Size)',
  'plus size': 'Ropa Especializada / Otros:Especializada:Tallas Extra (Plus Size)',

  // --- ELECTRONICA Y TECNOLOGIA ---
  // Celulares
  'celular': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'smartphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'samsung galaxy': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'celular basico': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celular reacondicionado': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares Reacondicionados',
  'funda celular': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'carcasa celular': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'protector pantalla': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'mica': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'cargador celular': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cable usb': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'power bank': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'bateria externa': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'soporte celular': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'smartband': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'correa smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',

  // Computacion
  'laptop': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'macbook': 'Electrónica y Tecnología:Computación:MacBooks',
  'notebook': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop gamer': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'ultrabook': 'Electrónica y Tecnología:Computación:Ultrabooks',
  'all in one': 'Electrónica y Tecnología:Computación:All-in-One',
  'computadora escritorio': 'Electrónica y Tecnología:Computación:All-in-One',
  'pc gamer': 'Electrónica y Tecnología:Computación:PC Gamer',
  'mini pc': 'Electrónica y Tecnología:Computación:Mini PCs',
  'disco duro': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'ssd': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'memoria ram': 'Electrónica y Tecnología:Computación:Memorias RAM',
  'procesador': 'Electrónica y Tecnología:Computación:Procesadores',
  'cpu': 'Electrónica y Tecnología:Computación:Procesadores',
  'tarjeta video': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'gpu': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'motherboard': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'tarjeta madre': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'fuente poder': 'Electrónica y Tecnología:Computación:Fuentes de Poder',
  'gabinete pc': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'monitor': 'Electrónica y Tecnología:Computación:Monitores',
  'teclado': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'mouse': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'raton': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'webcam': 'Electrónica y Tecnología:Computación:Webcams',
  'hub usb': 'Electrónica y Tecnología:Computación:Hubs USB y Adaptadores',
  'disco duro externo': 'Electrónica y Tecnología:Computación:Almacenamiento Externo',
  'memoria usb': 'Electrónica y Tecnología:Computación:Memorias USB',
  'pendrive': 'Electrónica y Tecnología:Computación:Memorias USB',
  'micro sd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'sd card': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'router': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'modem': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'repetidor wifi': 'Electrónica y Tecnología:Computación:Repetidores de Señal',
  'cable ethernet': 'Electrónica y Tecnología:Computación:Cables de Red',

  // TV Audio Video
  'smart tv': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'televisor': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'pantalla': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'soporte tv': 'Electrónica y Tecnología:TV, Audio y Video:Soportes para TV',
  'roku': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'chromecast': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'fire tv': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'audifonos': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'auriculares': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'bocina': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'parlante': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'barra sonido': 'Electrónica y Tecnología:TV, Audio y Video:Barras de Sonido',
  'home theater': 'Electrónica y Tecnología:TV, Audio y Video:Home Theater',
  'alexa': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'google home': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'proyector': 'Electrónica y Tecnología:TV, Audio y Video:Proyectores',

  // Camaras
  'camara dslr': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camara reflex': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camara mirrorless': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Mirrorless',
  'gopro': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camara accion': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camara instantanea': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'instax': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'drone': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'dron': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'lente camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Objetivos',
  'tripie': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',
  'aro luz': 'Electrónica y Tecnología:Cámaras y Fotografía:Iluminación de Estudio',
  'mochila camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Mochilas y Estuches',

  // Videojuegos
  'ps5': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'ps4': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'playstation': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'xbox': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'xbox series': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'nintendo switch': 'Electrónica y Tecnología:Videojuegos:Nintendo',
  'consola retro': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'videojuego': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego ps4': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego xbox': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego switch': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'tarjeta regalo': 'Electrónica y Tecnología:Videojuegos:Tarjetas de Regalo',
  'control ps4': 'Electrónica y Tecnología:Videojuegos:Controles',
  'control xbox': 'Electrónica y Tecnología:Videojuegos:Controles',
  'joycon': 'Electrónica y Tecnología:Videojuegos:Controles',
  'headset gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'audifonos gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'silla gamer': 'Electrónica y Tecnología:Videojuegos:Sillas Gamer',
  'volante gamer': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',

  // Oficina
  'impresora': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras',
  'multifuncional': 'Electrónica y Tecnología:Electrónica de Oficina:Multifuncionales',
  'escaner': 'Electrónica y Tecnología:Electrónica de Oficina:Escáneres',
  'impresora 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras 3D',
  'cartucho tinta': 'Electrónica y Tecnología:Electrónica de Oficina:Cartuchos de Tinta',
  'toner': 'Electrónica y Tecnología:Electrónica de Oficina:Tóners',
  'filamento 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Filamentos 3D',
  'calculadora': 'Electrónica y Tecnología:Electrónica de Oficina:Calculadoras',
  'trituradora': 'Electrónica y Tecnología:Electrónica de Oficina:Trituradoras',
  'telefono fijo': 'Electrónica y Tecnología:Electrónica de Oficina:Teléfonos Fijos',

  // --- HOGAR, JARDIN Y HERRAMIENTAS ---
  // Muebles
  'sofa': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sillon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'mesa centro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'mueble tv': 'Hogar, Jardín y Herramientas:Muebles y Organización:Muebles TV',
  'puff': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'cama': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'base cama': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'colchon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Colchones',
  'cabecera': 'Hogar, Jardín y Herramientas:Muebles y Organización:Cabeceras',
  'buro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'comoda': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'armario': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'ropero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'closet': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Juegos de Comedor',
  'mesa': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'silla': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'bufetera': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bufeteras',
  'banco barra': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bancos Barra',
  'escritorio': 'Hogar, Jardín y Herramientas:Muebles y Organización:Escritorios',
  'silla oficina': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sillas Oficina',
  'archivero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'librero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',

  // Cocina
  'olla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'cacerola': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'sarten': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'wok': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'olla presion': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas Presión',
  'molde hornear': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Moldes Hornear',
  'vajilla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'plato': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'vaso': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'copa': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'cubiertos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cubiertos',
  'mantel': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'servilleta tela': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'cuchillo cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tabla picar': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tupper': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'organizador cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Organizadores Cocina',
  'termo': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'cafetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cafeteras',
  'tetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',

  // Decoracion
  'lampara techo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Techo',
  'lampara mesa': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Mesa',
  'foco': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'tira led': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Tiras LED',
  'espejo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Espejos',
  'cuadro': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'reloj pared': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Relojes Pared',
  'vinilo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'cortina': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'persiana': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'alfombra': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'cojin': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cojines',
  'difusor aroma': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Difusores',
  'vela': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',

  // Cama y Baño
  'sabana': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Sábanas',
  'edredon': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'almohada': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'toalla': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Toallas',
  'cortina bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cortinas Baño',
  'tapete bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tapetes Baño',
  'cesto ropa': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cestos',
  'tendedero': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'tabla planchar': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tablas Planchar',
  'escoba': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Artículos Limpieza',
  'trapeador': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Artículos Limpieza',

  // Jardin
  'sala exterior': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Salas Exterior',
  'hamaca': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'sombrilla jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'asador carbon': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Carbón',
  'asador gas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Gas',
  'ahumador': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Ahumadores',
  'maceta': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'planta': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Plantas',
  'fertilizante': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sustratos',
  'semillas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Semillas',
  'manguera': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'cortadora cesped': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Cortadoras',
  'desbrozadora': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Desbrozadoras',
  'motosierra': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Motosierras',
  'alberca': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Albercas',
  'inflable': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Inflables Agua',

  // Herramientas
  'taladro': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'esmeriladora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Esmeriladoras',
  'sierra': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Sierras',
  'lijadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Lijadoras',
  'soldadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Soldadoras',
  'compresor': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Compresores',
  'kit herramientas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Kits Herramientas',
  'desarmador': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'martillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'alicate': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'pinza': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'cinta metrica': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Medición',
  'tornillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'pegamento': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cerradura': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'grifo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Grifería',
  'regadera': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'bomba agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Bombas Agua',
  'boiler': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'extension electrica': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'interruptor': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'cable electrico': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cableado',
  'zapato seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Zapatos Seguridad',
  'casco seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'chaleco seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Chalecos',

  // --- BELLEZA Y SALUD ---
  'skincare': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'crema facial': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'maquillaje': 'Belleza y Salud:Maquillaje:Rostro',
  'base maquillaje': 'Belleza y Salud:Maquillaje:Rostro',
  'labial': 'Belleza y Salud:Maquillaje:Labios',
  'sombras ojos': 'Belleza y Salud:Maquillaje:Ojos',
  'shampoo': 'Belleza y Salud:Cuidado del Cabello:Shampoo y Acondicionador',
  'acondicionador': 'Belleza y Salud:Cuidado del Cabello:Shampoo y Acondicionador',
  'perfume': 'Belleza y Salud:Perfumes y Fragancias:Mujer',
  'locion': 'Belleza y Salud:Perfumes y Fragancias:Hombre',
  'fragancia': 'Belleza y Salud:Perfumes y Fragancias:Unisex',
  'rasuradora': 'Belleza y Salud:Cuidado Personal:Rasuradoras y Depiladoras',
  'depiladora': 'Belleza y Salud:Cuidado Personal:Rasuradoras y Depiladoras',
  'secadora cabello': 'Belleza y Salud:Cuidado Personal:Secadoras y Alaciadoras',
  'alaciadora': 'Belleza y Salud:Cuidado Personal:Secadoras y Alaciadoras',

  // --- ALIMENTOS Y BEBIDAS ---
  'cerveza': 'Alimentos y Bebidas:Vinos y Licores:Cervezas',
  'tequila': 'Alimentos y Bebidas:Vinos y Licores:Tequila y Mezcal',
  'mezcal': 'Alimentos y Bebidas:Vinos y Licores:Tequila y Mezcal',
  'vino tinto': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'whisky': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'vodka': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'cafe grano': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'cafe molido': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'chocolate': 'Alimentos y Bebidas:Snacks:Chocolates',
  'dulce': 'Alimentos y Bebidas:Snacks:Dulces',
  'botana': 'Alimentos y Bebidas:Snacks:Botanas',
  'aceite cocina': 'Alimentos y Bebidas:Despensa:Aceites',
  'proteina': 'Alimentos y Bebidas:Saludable:Organico', // Approx
  'vitamina': 'Belleza y Salud:Salud:Vitaminas', // Better match in Health
  'creatina': 'Belleza y Salud:Salud:Vitaminas', // Better match in Health

  // --- DEPORTES Y FITNESS ---
  'mancuerna': 'Deportes y Aire Libre:Fitness:Pesas',
  'pesa': 'Deportes y Aire Libre:Fitness:Pesas',
  'barra gimnasio': 'Deportes y Aire Libre:Fitness:Pesas',
  'caminadora': 'Deportes y Aire Libre:Fitness:Cardio',
  'eliptica': 'Deportes y Aire Libre:Fitness:Cardio',
  'bicicleta': 'Deportes y Aire Libre:Ciclismo:Bicicletas',
  'casco bicicleta': 'Deportes y Aire Libre:Ciclismo:Accesorios Bici',
  'balon futbol': 'Deportes y Aire Libre:Deportes Equipo:Futbol',
  'balon basket': 'Deportes y Aire Libre:Deportes Equipo:Basket',
  'casa campaña': 'Deportes y Aire Libre:Camping:Camping',
  'tienda campaña': 'Deportes y Aire Libre:Camping:Camping',
  'caña pescar': 'Deportes y Aire Libre:Camping:Pesca',
  'raqueta': 'Deportes y Aire Libre:Raqueta:Tenis',
  'goggles': 'Deportes y Aire Libre:Acuaticos:Natacion',
  'patines': 'Deportes y Aire Libre:Patines:Patines',
  'skate': 'Deportes y Aire Libre:Patines:Skate',
  'guantes box': 'Deportes y Aire Libre:Artes Marciales:Boxeo',
  'costal box': 'Deportes y Aire Libre:Artes Marciales:Boxeo',

  // --- MASCOTAS ---
  'croquetas perro': 'Mascotas:Perros:Alimento',
  'alimento perro': 'Mascotas:Perros:Alimento',
  'juguete perro': 'Mascotas:Perros:Juguetes',
  'cama perro': 'Mascotas:Perros:Camas',
  'correa perro': 'Mascotas:Perros:Paseo',
  'collar perro': 'Mascotas:Perros:Paseo',
  'shampoo perro': 'Mascotas:Perros:Higiene',
  'croquetas gato': 'Mascotas:Gatos:Alimento Gato',
  'alimento gato': 'Mascotas:Gatos:Alimento Gato',
  'arena gato': 'Mascotas:Gatos:Arena',
  'rascador gato': 'Mascotas:Gatos:Muebles Gato',
  'juguete gato': 'Mascotas:Gatos:Juguetes Gato',
  'pecera': 'Mascotas:Acuarios:Peces Accesorios',
  'acuario': 'Mascotas:Acuarios:Peces Accesorios',

  // --- AUTOMOTRIZ ---
  'llanta': 'Automotriz y Motocicletas:Llantas:Llantas',
  'rin': 'Automotriz y Motocicletas:Llantas:Rines',
  'bateria auto': 'Automotriz y Motocicletas:Refacciones Auto:Electrico',
  'aceite motor': 'Automotriz y Motocicletas:Herramientas Auto:Aceites',
  'casco moto': 'Automotriz y Motocicletas:Motos:Equipamiento Moto',
  'faro': 'Automotriz y Motocicletas:Refacciones Auto:Electrico',
  'bujia': 'Automotriz y Motocicletas:Refacciones Auto:Motor',
  'amortiguador': 'Automotriz y Motocicletas:Refacciones Auto:Suspension',
  'balata': 'Automotriz y Motocicletas:Refacciones Auto:Frenos',

  // --- INDUSTRIA Y EMPRESAS ---
  'caja carton': 'Industria y Empresas:Embalaje:Material Empaque',
  'cinta canela': 'Industria y Empresas:Embalaje:Material Empaque',
  'playo': 'Industria y Empresas:Embalaje:Material Empaque',
  'burbuja': 'Industria y Empresas:Embalaje:Material Empaque',
  'impresora tickets': 'Industria y Empresas:Comercial:POS',
  'lector codigos': 'Industria y Empresas:Comercial:POS',
  'maniqui': 'Industria y Empresas:Comercial:Exhibicion',
  'papel higienico industrial': 'Industria y Empresas:Limpieza:Papel Inst',

  // --- ENTRETENIMIENTO Y CULTURA ---
  'libro': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'novela': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'comic': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'manga': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'guitarra': 'Entretenimiento, Arte y Cultura:Instrumentos:Guitarras',
  'piano': 'Entretenimiento, Arte y Cultura:Instrumentos:Teclados',
  'bateria musical': 'Entretenimiento, Arte y Cultura:Instrumentos:Baterias',
  'vinilo musica': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Vinilos',
  'disco vinilo': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Vinilos',

  // --- OTROS ---
  'juguete sexual': 'Otros:Adultos:Juguetes',
  'vibrador': 'Otros:Adultos:Juguetes',
  'lenceria erotica': 'Otros:Adultos:Lenceria',
  'antivirus': 'Otros:Restringidos:Software',
  'office': 'Otros:Restringidos:Software',
  'windows': 'Otros:Restringidos:Software',
  'tarjeta regalo digital': 'Otros:Restringidos:Suscripciones',
  
  // --- USER REQUESTED & MISSING ---
  'caja de carton': 'Industria y Empresas:Embalaje:Material Empaque',
  'celulares': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'consola': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'videojuegos': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'calzado': 'Mujer:Calzado', // Generic fallback
  'calzado mujer': 'Mujer:Calzado',
  'calzado hombre': 'Hombre:Calzado',
   'lipstick': 'Belleza y Salud:Maquillaje:Labios',
  'refresco': 'Alimentos y Bebidas:Bebidas:Aguas y Refrescos',
  'perfume hombre': 'Belleza y Salud:Perfumes:Hombre',
  'perfume mujer': 'Belleza y Salud:Perfumes:Mujer',

  // --- AUTO-GENERATED MAPPINGS FROM CATEGORY STRUCTURE ---
  'ropa': 'Mujer:Ropa',
  'zapatos': 'Mujer:Calzado',
  'tenis sneakersdeportivos': 'Mujer:Calzado:Tenis',
  'botas y botines': 'Mujer:Calzado:Botas',
  'botas': 'Mujer:Calzado:Botas',
  'botines': 'Mujer:Calzado:Botas',
  'sandalias y alpargatas': 'Mujer:Calzado:Sandalias',
  'sandalias': 'Mujer:Calzado:Sandalias',
  'alpargatas': 'Mujer:Calzado:Sandalias',
  'zapatos de tacon': 'Mujer:Calzado:Tacones',
  'flats y balerinas': 'Mujer:Calzado:Flats',
  'balerinas': 'Mujer:Calzado:Flats',
  'bolsas y carteras': 'Mujer:Bolsas',
  'bolsas': 'Mujer:Bolsas',
  'carteras': 'Mujer:Bolsas',
  'bolsas tote crossbody': 'Mujer:Bolsas:Bolsas',
  'bolsas tote': 'Mujer:Bolsas:Bolsas',
  'mochilas de moda': 'Mujer:Bolsas:Mochilas',
  'carteras y monederos': 'Mujer:Bolsas:Carteras',
  'monederos': 'Mujer:Bolsas:Carteras',
  'clutches y fiesta': 'Mujer:Bolsas:Clutches',
  'clutches': 'Mujer:Bolsas:Clutches',
  'fiesta': 'Mujer:Bolsas:Clutches',
  'zapatos de vestir': 'Hombre:Calzado:Zapatos Vestir',
  'sandalias y chanclas': 'Hombre:Calzado:Sandalias',
  'chanclas': 'Hombre:Calzado:Sandalias',
  'bebes 0  24 meses': 'Niños, Niñas y Bebés:Bebés',
  'bebes': 'Niños, Niñas y Bebés:Bebés',
  'zapatos suela blanda': 'Niños, Niñas y Bebés:Bebés:Zapatos Bebé',
  'accesorios baberos gorritos': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'accesorios baberos': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'gorritos': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'accesorios': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'ninas 2  16 anos': 'Niños, Niñas y Bebés:Niñas',
  'ninas': 'Niños, Niñas y Bebés:Niñas',
  'zapatos escolarescasual': 'Niños, Niñas y Bebés:Niñas:Zapatos Niña',
  'ninos 2  16 anos': 'Niños, Niñas y Bebés:Niños',
  'ninos': 'Niños, Niñas y Bebés:Niños',
  'relojes': 'Accesorios de Moda:Relojes',
  'relojes analogicos': 'Accesorios de Moda:Relojes:Analogicos',
  'relojes digitales': 'Accesorios de Moda:Relojes:Digitales',
  'relojes de lujo': 'Accesorios de Moda:Relojes:Lujo',
  'joyeria y bisuteria': 'Accesorios de Moda:Joyería',
  'bisuteria': 'Accesorios de Moda:Joyería',
  'collares y dijes': 'Accesorios de Moda:Joyería:Collares',
  'collares': 'Accesorios de Moda:Joyería:Collares',
  'dijes': 'Accesorios de Moda:Joyería:Collares',
  'aretes y broqueles': 'Accesorios de Moda:Joyería:Aretes',
  'aretes': 'Accesorios de Moda:Joyería:Aretes',
  'broqueles': 'Accesorios de Moda:Joyería:Aretes',
  'pulseras y brazaletes': 'Accesorios de Moda:Joyería:Pulseras',
  'pulseras': 'Accesorios de Moda:Joyería:Pulseras',
  'brazaletes': 'Accesorios de Moda:Joyería:Pulseras',
  'anillos': 'Accesorios de Moda:Joyería:Anillos',
  'joyeria fina oroplata': 'Accesorios de Moda:Joyería:Fina',
  'joyeria fina': 'Accesorios de Moda:Joyería:Fina',
  'bisuteria  fantasia': 'Accesorios de Moda:Joyería:Fantasia',
  'lentes de sol': 'Accesorios de Moda:Lentes:Sol',
  'armazones oftalmicos': 'Accesorios de Moda:Lentes:Oftalmicos',
  'equipaje y mochilas': 'Accesorios de Moda:Equipaje',
  'mochilas': 'Accesorios de Moda:Equipaje',
  'maletas de viaje': 'Accesorios de Moda:Equipaje:Maletas',
  'mochilas escolareslaptop': 'Accesorios de Moda:Equipaje:Mochilas',
  'bolsas de viaje': 'Accesorios de Moda:Equipaje:Bolsas Viaje',
  'cangureras': 'Accesorios de Moda:Equipaje:Cangureras',
  'accesorios varios': 'Accesorios de Moda:Varios',
  'cinturones': 'Accesorios de Moda:Varios:Cinturones',
  'gorras y sombreros': 'Accesorios de Moda:Varios:Gorras',
  'gorras': 'Accesorios de Moda:Varios:Gorras',
  'sombreros': 'Accesorios de Moda:Varios:Gorras',
  'bufandas y panuelos': 'Accesorios de Moda:Varios:Bufandas',
  'bufandas': 'Accesorios de Moda:Varios:Bufandas',
  'panuelos': 'Accesorios de Moda:Varios:Bufandas',
  'ropa especializada': 'Ropa Especializada / Otros:Especializada',
  'celulares y telefonia': 'Electrónica y Tecnología:Celulares y Telefonía',
  'telefonia': 'Electrónica y Tecnología:Celulares y Telefonía',
  'smartphones android  ios': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'smartphones': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'celulares basicos feature phones': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celulares basicos': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celulares reacondicionados': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares Reacondicionados',
  'fundas y carcasas': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'fundas': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'carcasas': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'micas y protectores de pantalla': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'micas': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'protectores de pantalla': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'cargadores y cables': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cargadores': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cables': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'power banks baterias externas': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'power banks': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'soportes auto escritorio': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'soportes auto': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'soportes': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'relojes inteligentes': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'pulseras de actividad smartbands': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'pulseras de actividad': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'correas y cargadores para smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',
  'correas': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',
  'cargadores para smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',
  'computacion informatica': 'Electrónica y Tecnología:Computación',
  'computacion': 'Electrónica y Tecnología:Computación',
  'laptops tradicionales': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptops gamer': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'ultrabooks  2 en 1': 'Electrónica y Tecnología:Computación:Ultrabooks',
  'macbooks': 'Electrónica y Tecnología:Computación:MacBooks',
  'allinone todo en uno': 'Electrónica y Tecnología:Computación:All-in-One',
  'allinone': 'Electrónica y Tecnología:Computación:All-in-One',
  'pc gamer torres armadas': 'Electrónica y Tecnología:Computación:PC Gamer',
  'mini pcs': 'Electrónica y Tecnología:Computación:Mini PCs',
  'discos duros y ssd internos': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'discos duros': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'ssd internos': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'memorias ram': 'Electrónica y Tecnología:Computación:Memorias RAM',
  'procesadores cpu': 'Electrónica y Tecnología:Computación:Procesadores',
  'procesadores': 'Electrónica y Tecnología:Computación:Procesadores',
  'tarjetas de video gpu': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'tarjetas de video': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'tarjetas madre motherboards': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'tarjetas madre': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'fuentes de poder': 'Electrónica y Tecnología:Computación:Fuentes de Poder',
  'gabinetes y enfriamiento': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'gabinetes': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'enfriamiento': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'monitores': 'Electrónica y Tecnología:Computación:Monitores',
  'teclados y mouses': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'teclados': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'mouses': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'webcams': 'Electrónica y Tecnología:Computación:Webcams',
  'hubs usb y adaptadores': 'Electrónica y Tecnología:Computación:Hubs USB y Adaptadores',
  'hubs usb': 'Electrónica y Tecnología:Computación:Hubs USB y Adaptadores',
  'adaptadores': 'Electrónica y Tecnología:Computación:Hubs USB y Adaptadores',
  'discos duros externos': 'Electrónica y Tecnología:Computación:Almacenamiento Externo',
  'memorias usb pendrives': 'Electrónica y Tecnología:Computación:Memorias USB',
  'memorias usb': 'Electrónica y Tecnología:Computación:Memorias USB',
  'tarjetas de memoria sd microsd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'tarjetas de memoria sd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'microsd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'tarjetas de memoria': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'routers y modems': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'routers': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'modems': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'repetidores de senal wifi  mesh': 'Electrónica y Tecnología:Computación:Repetidores de Señal',
  'cables de red ethernet': 'Electrónica y Tecnología:Computación:Cables de Red',
  'cables de red': 'Electrónica y Tecnología:Computación:Cables de Red',
  'tv audio y video': 'Electrónica y Tecnología:TV, Audio y Video',
  'tv audio': 'Electrónica y Tecnología:TV, Audio y Video',
  'video': 'Electrónica y Tecnología:TV, Audio y Video',
  'audio y video': 'Electrónica y Tecnología:TV, Audio y Video',
  'smart tvs 4k 8k oled': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'smart tvs 4k': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'oled': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'smart tvs': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'soportes para tv': 'Electrónica y Tecnología:TV, Audio y Video:Soportes para TV',
  'dispositivos de streaming roku etc': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'dispositivos de streaming roku': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'etc': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'dispositivos de streaming': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'bocinas portatiles bluetooth': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'bocinas portatiles': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'barras de sonido': 'Electrónica y Tecnología:TV, Audio y Video:Barras de Sonido',
  'asistentes de voz': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'proyectores de cine en casa': 'Electrónica y Tecnología:TV, Audio y Video:Proyectores',
  'mini proyectores portatiles': 'Electrónica y Tecnología:TV, Audio y Video:Mini Proyectores',
  'camaras y fotografia': 'Electrónica y Tecnología:Cámaras y Fotografía',
  'camaras': 'Electrónica y Tecnología:Cámaras y Fotografía',
  'fotografia': 'Electrónica y Tecnología:Cámaras y Fotografía',
  'camaras dslr reflex': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camaras dslr': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camaras mirrorless sin espejo': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Mirrorless',
  'camaras mirrorless': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Mirrorless',
  'camaras de accion gopro': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camaras de accion': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camaras instantaneas': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'drones con camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'refacciones para drones': 'Electrónica y Tecnología:Cámaras y Fotografía:Refacciones para drones',
  'objetivos  lentes': 'Electrónica y Tecnología:Cámaras y Fotografía:Objetivos',
  'tripies y estabilizadores': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',
  'tripies': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',
  'estabilizadores': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',
  'iluminacion de estudio': 'Electrónica y Tecnología:Cámaras y Fotografía:Iluminación de Estudio',
  'mochilas y estuches para camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Mochilas y Estuches',
  'estuches para camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Mochilas y Estuches',
  'videojuegos gaming': 'Electrónica y Tecnología:Videojuegos',
  'playstation ps5 ps4': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'playstation ps5': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'xbox series xs one': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'xbox series xs': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'one': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'nintendo': 'Electrónica y Tecnología:Videojuegos:Nintendo',
  'consolas retro  arcade': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'juegos fisicos': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'tarjetas de regalo  digitales': 'Electrónica y Tecnología:Videojuegos:Tarjetas de Regalo',
  'controles mandos': 'Electrónica y Tecnología:Videojuegos:Controles',
  'controles': 'Electrónica y Tecnología:Videojuegos:Controles',
  'headsets gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'sillas gamer': 'Electrónica y Tecnología:Videojuegos:Sillas Gamer',
  'volantes y pedales': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',
  'volantes': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',
  'pedales': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',
  'electronica de oficina': 'Electrónica y Tecnología:Electrónica de Oficina',
  'impresoras': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras',
  'multifuncionales': 'Electrónica y Tecnología:Electrónica de Oficina:Multifuncionales',
  'escaneres': 'Electrónica y Tecnología:Electrónica de Oficina:Escáneres',
  'impresoras 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras 3D',
  'cartuchos de tinta': 'Electrónica y Tecnología:Electrónica de Oficina:Cartuchos de Tinta',
  'toners': 'Electrónica y Tecnología:Electrónica de Oficina:Tóners',
  'filamentos para 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Filamentos 3D',
  'calculadoras cientificasfinancieras': 'Electrónica y Tecnología:Electrónica de Oficina:Calculadoras',
  'trituradoras de papel': 'Electrónica y Tecnología:Electrónica de Oficina:Trituradoras',
  'telefonos fijos  ip': 'Electrónica y Tecnología:Electrónica de Oficina:Teléfonos Fijos',
  'muebles y organizacion hogar': 'Hogar, Jardín y Herramientas:Muebles y Organización',
  'muebles': 'Hogar, Jardín y Herramientas:Muebles y Organización',
  'organizacion hogar': 'Hogar, Jardín y Herramientas:Muebles y Organización',
  'muebles y organizacion': 'Hogar, Jardín y Herramientas:Muebles y Organización',
  'sala sofas y sillones': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sala sofas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sillones': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sala mesas de centro y laterales': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'sala mesas de centro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'laterales': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'sala muebles para tv': 'Hogar, Jardín y Herramientas:Muebles y Organización:Muebles TV',
  'sala puffs y taburetes': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'sala puffs': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'taburetes': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'recamara camas y bases': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'recamara camas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'bases': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'recamara colchones': 'Hogar, Jardín y Herramientas:Muebles y Organización:Colchones',
  'recamara cabeceras': 'Hogar, Jardín y Herramientas:Muebles y Organización:Cabeceras',
  'recamara buros y comodas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'recamara buros': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'comodas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'recamara armarios y roperos': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'recamara armarios': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'roperos': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'comedor juegos de comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Juegos de Comedor',
  'comedor mesas y sillas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'comedor mesas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'sillas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'comedor bufeteras': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bufeteras',
  'comedor bancos para barra': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bancos Barra',
  'oficina escritorios': 'Hogar, Jardín y Herramientas:Muebles y Organización:Escritorios',
  'oficina sillas': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sillas Oficina',
  'oficina archiveros y libreros': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'oficina archiveros': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'libreros': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'cocina y mesa bazar': 'Hogar, Jardín y Herramientas:Cocina y Mesa',
  'cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa',
  'mesa bazar': 'Hogar, Jardín y Herramientas:Cocina y Mesa',
  'cocina y mesa': 'Hogar, Jardín y Herramientas:Cocina y Mesa',
  'ollas y cacerolas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'ollas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'cacerolas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'sartenes y woks': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'sartenes': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'woks': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'ollas de presion': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas Presión',
  'moldes para hornear': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Moldes Hornear',
  'juegos de vajilla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'vasos copas y jarras': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'vasos copas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'jarras': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'vasos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'copas y jarras': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'servilletas y manteles': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'servilletas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'manteles': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'cuchillos y tablas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'cuchillos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tablas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'recipientes y tuppers': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'recipientes': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'tuppers': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'organizadores de cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Organizadores Cocina',
  'termos y botellas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'termos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'botellas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'cafeteras manualesgoteo': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cafeteras',
  'cafeteras': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cafeteras',
  'teteras y hervidores': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',
  'teteras': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',
  'hervidores': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',
  'molinillos de cafe': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Molinillos',
  'decoracion e iluminacion': 'Hogar, Jardín y Herramientas:Decoración e Iluminación',
  'lamparas de techocolgantes': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Techo',
  'lamparas de pie y mesa': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Mesa',
  'lamparas de pie': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Mesa',
  'focos y bombillas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'focos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'bombillas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'tiras led': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Tiras LED',
  'espejos decorativos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Espejos',
  'cuadros y marcos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'cuadros': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'marcos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'relojes de pared': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Relojes Pared',
  'vinilos y papel tapiz': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'vinilos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'papel tapiz': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'cortinas y persianas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'cortinas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'persianas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'alfombras y tapetes': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'alfombras': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'tapetes': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'cojines decorativos': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cojines',
  'difusores de aroma': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Difusores',
  'velas y candelabros': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',
  'velas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',
  'candelabros': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',
  'cama bano y limpieza': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza',
  'cama bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza',
  'limpieza': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza',
  'bano y limpieza': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza',
  'juegos de sabanas': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Sábanas',
  'edredones y duvets': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'edredones': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'duvets': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'almohadas y protectores': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'almohadas': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'protectores': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'toallas': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Toallas',
  'cortinas de bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cortinas Baño',
  'accesorios de bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Accesorios Baño',
  'tapetes de bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tapetes Baño',
  'cestos de ropa': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cestos',
  'tendederos y ganchos': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'tendederos': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'ganchos': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'tablas de planchar': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tablas Planchar',
  'articulos de limpieza': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Artículos Limpieza',
  'jardin y aire libre': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre',
  'jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre',
  'aire libre': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre',
  'salas de exterior': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Salas Exterior',
  'comedores de jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Comedores Jardín',
  'hamacas y tumbonas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'hamacas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'tumbonas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'sombrillas y toldos': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'sombrillas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'toldos': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'asadores de carbonlena': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Carbón',
  'asadores de gas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Gas',
  'ahumadores': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Ahumadores',
  'utensilios para asar': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Utensilios Asar',
  'macetas y jardineras': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'macetas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'jardineras': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'plantas naturalesartificiales': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Plantas',
  'plantas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Plantas',
  'sustratos y fertilizantes': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sustratos',
  'sustratos': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sustratos',
  'fertilizantes': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sustratos',
  'mangueras y riego': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'mangueras': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'riego': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'cortadoras de cesped': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Cortadoras',
  'desbrozadoras': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Desbrozadoras',
  'sopladoras de hojas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sopladoras',
  'motosierras': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Motosierras',
  'albercas inflablesestructurales': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Albercas',
  'inflables y juguetes de agua': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Inflables Agua',
  'inflables': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Inflables Agua',
  'juguetes de agua': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Inflables Agua',
  'quimicos y limpieza de piscinas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Químicos Alberca',
  'quimicos': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Químicos Alberca',
  'limpieza de piscinas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Químicos Alberca',
  'herramientas y mejoras del hogar': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras',
  'herramientas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras',
  'mejoras del hogar': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras',
  'taladros y atornilladores': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'taladros': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'atornilladores': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'esmeriladoras': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Esmeriladoras',
  'sierras': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Sierras',
  'lijadoras': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Lijadoras',
  'soldadoras': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Soldadoras',
  'compresores de aire': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Compresores',
  'juegos de herramientas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Kits Herramientas',
  'desarmadores y llaves': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'desarmadores': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'llaves': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'martillos y mazos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'martillos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'mazos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'alicates y pinzas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'alicates': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'pinzas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'instrumentos de medicion': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Medición',
  'tornillos y fijaciones': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'tornillos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'fijaciones': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'cintas y pegamentos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cintas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'pegamentos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cerraduras y herrajes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'cerraduras': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'herrajes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'griferia': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Grifería',
  'regaderas y duchas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'regaderas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'duchas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'bombas de agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Bombas Agua',
  'calentadores de agua boilers': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'calentadores de agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'extensiones y multicontactos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'extensiones': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'multicontactos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'interruptores y enchufes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'interruptores': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'enchufes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'cableado electrico': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cableado',
  'fusibles y centros de carga': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Fusibles',
  'fusibles': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Fusibles',
  'centros de carga': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Fusibles',
  'zapatos de seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Zapatos Seguridad',
  'cascos lentes y guantes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'cascos lentes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'guantes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'cascos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'lentes y guantes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'chalecos reflejantes': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Chalecos',
  'cuidado de la piel skincare': 'Belleza y Salud:Cuidado de la Piel',
  'cuidado de la piel': 'Belleza y Salud:Cuidado de la Piel',
  'limpiadores y desmaquillantes': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'limpiadores': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'desmaquillantes': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'tonicos y brumas': 'Belleza y Salud:Cuidado de la Piel:Tonicos',
  'tonicos': 'Belleza y Salud:Cuidado de la Piel:Tonicos',
  'brumas': 'Belleza y Salud:Cuidado de la Piel:Tonicos',
  'serums y tratamientos': 'Belleza y Salud:Cuidado de la Piel:Serums',
  'serums': 'Belleza y Salud:Cuidado de la Piel:Serums',
  'tratamientos': 'Belleza y Salud:Cuidado de la Piel:Serums',
  'cremas hidratantes': 'Belleza y Salud:Cuidado de la Piel:Cremas',
  'contorno de ojos': 'Belleza y Salud:Cuidado de la Piel:Ojos',
  'mascarillas': 'Belleza y Salud:Cuidado de la Piel:Mascarillas',
  'exfoliantes faciales': 'Belleza y Salud:Cuidado de la Piel:Exfoliantes',
  'proteccion solar': 'Belleza y Salud:Cuidado de la Piel:Proteccion Solar',
  'cuidado corporal cremasaceites': 'Belleza y Salud:Cuidado de la Piel:Cuerpo',
  'cuidado corporal': 'Belleza y Salud:Cuidado de la Piel:Cuerpo',
  'bases y correctores': 'Belleza y Salud:Maquillaje:Bases',
  'correctores': 'Belleza y Salud:Maquillaje:Bases',
  'polvos y rubores': 'Belleza y Salud:Maquillaje:Polvos',
  'polvos': 'Belleza y Salud:Maquillaje:Polvos',
  'rubores': 'Belleza y Salud:Maquillaje:Polvos',
  'iluminadores y bronzers': 'Belleza y Salud:Maquillaje:Iluminadores',
  'iluminadores': 'Belleza y Salud:Maquillaje:Iluminadores',
  'bronzers': 'Belleza y Salud:Maquillaje:Iluminadores',
  'ojos sombras delineadores rimel': 'Belleza y Salud:Maquillaje:Ojos',
  'ojos sombras': 'Belleza y Salud:Maquillaje:Ojos',
  'delineadores': 'Belleza y Salud:Maquillaje:Ojos',
  'rimel': 'Belleza y Salud:Maquillaje:Ojos',
  'ojos': 'Belleza y Salud:Maquillaje:Ojos',
  'cejas': 'Belleza y Salud:Maquillaje:Cejas',
  'labiales y balsamos': 'Belleza y Salud:Maquillaje:Labios',
  'labiales': 'Belleza y Salud:Maquillaje:Labios',
  'balsamos': 'Belleza y Salud:Maquillaje:Labios',
  'herramientas y brochas': 'Belleza y Salud:Maquillaje:Brochas',
  'brochas': 'Belleza y Salud:Maquillaje:Brochas',
  'cuidado del cabello': 'Belleza y Salud:Cabello',
  'shampoo y acondicionador': 'Belleza y Salud:Cabello:Shampoo',
  'tratamientos y mascarillas': 'Belleza y Salud:Cabello:Tratamientos',
  'tintes y coloracion': 'Belleza y Salud:Cabello:Coloracion',
  'tintes': 'Belleza y Salud:Cabello:Coloracion',
  'coloracion': 'Belleza y Salud:Cabello:Coloracion',
  'peinado gel spray': 'Belleza y Salud:Cabello:Peinado',
  'peinado gel': 'Belleza y Salud:Cabello:Peinado',
  'spray': 'Belleza y Salud:Cabello:Peinado',
  'peinado': 'Belleza y Salud:Cabello:Peinado',
  'aparatos secadoras planchas': 'Belleza y Salud:Cabello:Herramientas',
  'aparatos secadoras': 'Belleza y Salud:Cabello:Herramientas',
  'planchas': 'Belleza y Salud:Cabello:Herramientas',
  'aparatos': 'Belleza y Salud:Cabello:Herramientas',
  'perfumes y fragancias': 'Belleza y Salud:Perfumes',
  'perfumes': 'Belleza y Salud:Perfumes',
  'fragancias': 'Belleza y Salud:Perfumes',
  'perfumes mujer': 'Belleza y Salud:Perfumes:Mujer',
  'perfumes hombre': 'Belleza y Salud:Perfumes:Hombre',
  'perfumes unisex': 'Belleza y Salud:Perfumes:Unisex',
  'body mists': 'Belleza y Salud:Perfumes:Body Mists',
  'cuidado personal e higiene': 'Belleza y Salud:Cuidado Personal',
  'cuidado bucal': 'Belleza y Salud:Cuidado Personal:Bucal',
  'desodorantes': 'Belleza y Salud:Cuidado Personal:Desodorantes',
  'afeitado y depilacion': 'Belleza y Salud:Cuidado Personal:Afeitado',
  'afeitado': 'Belleza y Salud:Cuidado Personal:Afeitado',
  'depilacion': 'Belleza y Salud:Cuidado Personal:Afeitado',
  'higiene femenina': 'Belleza y Salud:Cuidado Personal:Higiene Fem',
  'manicure y pedicure': 'Belleza y Salud:Cuidado Personal:Uñas',
  'manicure': 'Belleza y Salud:Cuidado Personal:Uñas',
  'pedicure': 'Belleza y Salud:Cuidado Personal:Uñas',
  'salud y bienestar': 'Belleza y Salud:Salud',
  'salud': 'Belleza y Salud:Salud',
  'bienestar': 'Belleza y Salud:Salud',
  'vitaminas y suplementos': 'Belleza y Salud:Salud:Vitaminas',
  'vitaminas': 'Belleza y Salud:Salud:Vitaminas',
  'suplementos': 'Belleza y Salud:Salud:Vitaminas',
  'botiquin y primeros auxilios': 'Belleza y Salud:Salud:Botiquin',
  'botiquin': 'Belleza y Salud:Salud:Botiquin',
  'primeros auxilios': 'Belleza y Salud:Salud:Botiquin',
  'equipamiento medico hogar': 'Belleza y Salud:Salud:Equipo Medico',
  'bienestar sexual': 'Belleza y Salud:Salud:Sexual',
  'ortopedia y rehabilitacion': 'Belleza y Salud:Salud:Ortopedia',
  'ortopedia': 'Belleza y Salud:Salud:Ortopedia',
  'rehabilitacion': 'Belleza y Salud:Salud:Ortopedia',
  'bebes mundo bebe  puericultura': 'Bebé y Juguetes:Bebé',
  'paseo y viaje carriolas autoasientos': 'Bebé y Juguetes:Bebé:Paseo',
  'paseo': 'Bebé y Juguetes:Bebé:Paseo',
  'viaje carriolas autoasientos': 'Bebé y Juguetes:Bebé:Paseo',
  'paseo y viaje carriolas': 'Bebé y Juguetes:Bebé:Paseo',
  'autoasientos': 'Bebé y Juguetes:Bebé:Paseo',
  'paseo y viaje': 'Bebé y Juguetes:Bebé:Paseo',
  'lactancia y alimentacion': 'Bebé y Juguetes:Bebé:Lactancia',
  'lactancia': 'Bebé y Juguetes:Bebé:Lactancia',
  'alimentacion': 'Bebé y Juguetes:Bebé:Lactancia',
  'panales y cambio': 'Bebé y Juguetes:Bebé:Pañales',
  'panales': 'Bebé y Juguetes:Bebé:Pañales',
  'cambio': 'Bebé y Juguetes:Bebé:Pañales',
  'hora del bano': 'Bebé y Juguetes:Bebé:Baño',
  'salud y cuidado': 'Bebé y Juguetes:Bebé:Salud Bebe',
  'cuidado': 'Bebé y Juguetes:Bebé:Salud Bebe',
  'cuarto del bebe cunas monitores': 'Bebé y Juguetes:Bebé:Cuarto',
  'cuarto del bebe cunas': 'Bebé y Juguetes:Bebé:Cuarto',
  'cuarto del bebe': 'Bebé y Juguetes:Bebé:Cuarto',
  'juguetes y juegos': 'Bebé y Juguetes:Juguetes',
  'juguetes': 'Bebé y Juguetes:Juguetes',
  'juegos': 'Bebé y Juguetes:Juguetes',
  'construccion y bloques': 'Bebé y Juguetes:Juguetes:Construccion',
  'construccion': 'Bebé y Juguetes:Juguetes:Construccion',
  'bloques': 'Bebé y Juguetes:Juguetes:Construccion',
  'munecas y peluches': 'Bebé y Juguetes:Juguetes:Muñecas',
  'munecas': 'Bebé y Juguetes:Juguetes:Muñecas',
  'peluches': 'Bebé y Juguetes:Juguetes:Muñecas',
  'figuras de accion': 'Bebé y Juguetes:Juguetes:Figuras',
  'vehiculos y pistas': 'Bebé y Juguetes:Juguetes:Vehiculos',
  'vehiculos': 'Bebé y Juguetes:Juguetes:Vehiculos',
  'pistas': 'Bebé y Juguetes:Juguetes:Vehiculos',
  'juegos de mesa y rompecabezas': 'Bebé y Juguetes:Juguetes:Juegos Mesa',
  'juegos de mesa': 'Bebé y Juguetes:Juguetes:Juegos Mesa',
  'rompecabezas': 'Bebé y Juguetes:Juguetes:Juegos Mesa',
  'aire libre y montables': 'Bebé y Juguetes:Juguetes:Aire Libre',
  'montables': 'Bebé y Juguetes:Juguetes:Aire Libre',
  'arte manualidades y educativos': 'Bebé y Juguetes:Juguetes:Arte',
  'arte manualidades': 'Bebé y Juguetes:Juguetes:Arte',
  'educativos': 'Bebé y Juguetes:Juguetes:Arte',
  'arte': 'Bebé y Juguetes:Juguetes:Arte',
  'manualidades y educativos': 'Bebé y Juguetes:Juguetes:Arte',
  'primera infancia 03 anos': 'Bebé y Juguetes:Juguetes:Primera Infancia',
  'primera infancia': 'Bebé y Juguetes:Juguetes:Primera Infancia',
  'libros y revistas': 'Entretenimiento, Arte y Cultura:Libros',
  'libros': 'Entretenimiento, Arte y Cultura:Libros',
  'revistas': 'Entretenimiento, Arte y Cultura:Libros',
  'literatura y ficcion': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'literatura': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'ficcion': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'infantil y juvenil': 'Entretenimiento, Arte y Cultura:Libros:Infantil',
  'juvenil': 'Entretenimiento, Arte y Cultura:Libros:Infantil',
  'comics y manga': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'comics': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'academicos y texto': 'Entretenimiento, Arte y Cultura:Libros:Academicos',
  'academicos': 'Entretenimiento, Arte y Cultura:Libros:Academicos',
  'texto': 'Entretenimiento, Arte y Cultura:Libros:Academicos',
  'arte y fotografia': 'Entretenimiento, Arte y Cultura:Libros:Arte',
  'revistas y periodicos': 'Entretenimiento, Arte y Cultura:Libros:Revistas',
  'periodicos': 'Entretenimiento, Arte y Cultura:Libros:Revistas',
  'instrumentos musicales': 'Entretenimiento, Arte y Cultura:Instrumentos',
  'guitarras y bajos': 'Entretenimiento, Arte y Cultura:Instrumentos:Guitarras',
  'guitarras': 'Entretenimiento, Arte y Cultura:Instrumentos:Guitarras',
  'bajos': 'Entretenimiento, Arte y Cultura:Instrumentos:Guitarras',
  'teclados y pianos': 'Entretenimiento, Arte y Cultura:Instrumentos:Teclados',
  'pianos': 'Entretenimiento, Arte y Cultura:Instrumentos:Teclados',
  'baterias y percusion': 'Entretenimiento, Arte y Cultura:Instrumentos:Baterias',
  'baterias': 'Entretenimiento, Arte y Cultura:Instrumentos:Baterias',
  'percusion': 'Entretenimiento, Arte y Cultura:Instrumentos:Baterias',
  'audio profesional y grabacion': 'Entretenimiento, Arte y Cultura:Instrumentos:Audio Pro',
  'audio profesional': 'Entretenimiento, Arte y Cultura:Instrumentos:Audio Pro',
  'grabacion': 'Entretenimiento, Arte y Cultura:Instrumentos:Audio Pro',
  'instrumentos de viento y orquesta': 'Entretenimiento, Arte y Cultura:Instrumentos:Viento',
  'instrumentos de viento': 'Entretenimiento, Arte y Cultura:Instrumentos:Viento',
  'orquesta': 'Entretenimiento, Arte y Cultura:Instrumentos:Viento',
  'arte manualidades y costura': 'Entretenimiento, Arte y Cultura:Arte y Manualidades',
  'costura': 'Entretenimiento, Arte y Cultura:Arte y Manualidades',
  'manualidades y costura': 'Entretenimiento, Arte y Cultura:Arte y Manualidades',
  'pintura y dibujo': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Pintura',
  'pintura': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Pintura',
  'dibujo': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Pintura',
  'costura y tejido': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Costura',
  'tejido': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Costura',
  'manualidades y scrapbooking': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Manualidades',
  'manualidades': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Manualidades',
  'scrapbooking': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Manualidades',
  'insumos para joyeria': 'Entretenimiento, Arte y Cultura:Arte y Manualidades:Joyeria Insumos',
  'musica y peliculas fisico': 'Entretenimiento, Arte y Cultura:Musica y Peliculas',
  'musica': 'Entretenimiento, Arte y Cultura:Musica y Peliculas',
  'peliculas fisico': 'Entretenimiento, Arte y Cultura:Musica y Peliculas',
  'musica y peliculas': 'Entretenimiento, Arte y Cultura:Musica y Peliculas',
  'vinilos lps': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Vinilos',
  'cds y cassettes': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:CDs',
  'cds': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:CDs',
  'cassettes': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:CDs',
  'peliculas bluray  4k  dvd': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Peliculas',
  'peliculas': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Peliculas',
  'arte y coleccionables': 'Entretenimiento, Arte y Cultura:Coleccionables',
  'coleccionables': 'Entretenimiento, Arte y Cultura:Coleccionables',
  'arte original pinturasesculturas': 'Entretenimiento, Arte y Cultura:Coleccionables:Arte Original',
  'arte original': 'Entretenimiento, Arte y Cultura:Coleccionables:Arte Original',
  'antiguedades': 'Entretenimiento, Arte y Cultura:Coleccionables:Antiguedades',
  'numismatica y filatelia': 'Entretenimiento, Arte y Cultura:Coleccionables:Numismatica',
  'numismatica': 'Entretenimiento, Arte y Cultura:Coleccionables:Numismatica',
  'filatelia': 'Entretenimiento, Arte y Cultura:Coleccionables:Numismatica',
  'memorabilia y utileria': 'Entretenimiento, Arte y Cultura:Coleccionables:Memorabilia',
  'memorabilia': 'Entretenimiento, Arte y Cultura:Coleccionables:Memorabilia',
  'utileria': 'Entretenimiento, Arte y Cultura:Coleccionables:Memorabilia',
  'gastronomia y hoteleria': 'Industria y Empresas:Gastronomia',
  'gastronomia': 'Industria y Empresas:Gastronomia',
  'hoteleria': 'Industria y Empresas:Gastronomia',
  'coccion industrial': 'Industria y Empresas:Gastronomia:Coccion',
  'refrigeracion comercial': 'Industria y Empresas:Gastronomia:Refrigeracion',
  'preparacion de alimentos': 'Industria y Empresas:Gastronomia:Preparacion',
  'mobiliario acero inoxidable': 'Industria y Empresas:Gastronomia:Mobiliario Inox',
  'embalaje y logistica': 'Industria y Empresas:Embalaje',
  'embalaje': 'Industria y Empresas:Embalaje',
  'logistica': 'Industria y Empresas:Embalaje',
  'material de empaque': 'Industria y Empresas:Embalaje:Material Empaque',
  'etiquetado': 'Industria y Empresas:Embalaje:Etiquetado',
  'manejo de materiales': 'Industria y Empresas:Embalaje:Manejo Materiales',
  'suministros de oficina': 'Industria y Empresas:Oficina',
  'papel y consumibles': 'Industria y Empresas:Oficina:Papel',
  'papel': 'Industria y Empresas:Oficina:Papel',
  'consumibles': 'Industria y Empresas:Oficina:Papel',
  'equipamiento de oficina': 'Industria y Empresas:Oficina:Equipamiento',
  'seguridad industrial': 'Industria y Empresas:Seguridad',
  'proteccion personal epp': 'Industria y Empresas:Seguridad:Proteccion',
  'proteccion personal': 'Industria y Empresas:Seguridad:Proteccion',
  'senalizacion y seguridad vial': 'Industria y Empresas:Seguridad:Senalizacion',
  'senalizacion': 'Industria y Empresas:Seguridad:Senalizacion',
  'seguridad vial': 'Industria y Empresas:Seguridad:Senalizacion',
  'equipamiento medico profesional': 'Industria y Empresas:Medico',
  'mobiliario medico': 'Industria y Empresas:Medico:Mobiliario Med',
  'insumos desechables': 'Industria y Empresas:Medico:Insumos',
  'equipamiento comercial': 'Industria y Empresas:Comercial',
  'punto de venta pos': 'Industria y Empresas:Comercial:POS',
  'punto de venta': 'Industria y Empresas:Comercial:POS',
  'exhibicion y maniquies': 'Industria y Empresas:Comercial:Exhibicion',
  'exhibicion': 'Industria y Empresas:Comercial:Exhibicion',
  'maniquies': 'Industria y Empresas:Comercial:Exhibicion',
  'limpieza institucional': 'Industria y Empresas:Limpieza',
  'quimicos a granel': 'Industria y Empresas:Limpieza:Quimicos',
  'papel higienico institucional': 'Industria y Empresas:Limpieza:Papel Inst',
  'maquinaria de limpieza': 'Industria y Empresas:Limpieza:Maquinaria',
  'agroindustria y ganaderia': 'Industria y Empresas:Agroindustria',
  'agroindustria': 'Industria y Empresas:Agroindustria',
  'ganaderia': 'Industria y Empresas:Agroindustria',
  'cultivo': 'Industria y Empresas:Agroindustria:Cultivo',
  'maquinaria ligera': 'Industria y Empresas:Agroindustria:Maquinaria Agro',
  'perros articulos y alimento': 'Mascotas:Perros',
  'perros articulos': 'Mascotas:Perros',
  'alimento': 'Mascotas:Perros',
  'perros': 'Mascotas:Perros',
  'alimento y premios': 'Mascotas:Perros:Alimento',
  'premios': 'Mascotas:Perros:Alimento',
  'viaje': 'Mascotas:Perros:Paseo',
  'camas y muebles': 'Mascotas:Perros:Camas',
  'camas': 'Mascotas:Perros:Camas',
  'higiene y estetica': 'Mascotas:Perros:Higiene',
  'higiene': 'Mascotas:Perros:Higiene',
  'estetica': 'Mascotas:Perros:Higiene',
  'ropa y accesorios': 'Mascotas:Perros:Ropa',
  'gatos articulos y alimento': 'Mascotas:Gatos',
  'gatos articulos': 'Mascotas:Gatos',
  'gatos': 'Mascotas:Gatos',
  'arena y limpieza': 'Mascotas:Gatos:Arena',
  'arena': 'Mascotas:Gatos:Arena',
  'muebles y rascadores': 'Mascotas:Gatos:Muebles Gato',
  'rascadores': 'Mascotas:Gatos:Muebles Gato',
  'higiene y salud': 'Mascotas:Gatos:Higiene Gato',
  'acuarios y terrarios': 'Mascotas:Acuarios',
  'acuarios': 'Mascotas:Acuarios',
  'terrarios': 'Mascotas:Acuarios',
  'acuarios y filtros': 'Mascotas:Acuarios:Peces Accesorios',
  'filtros': 'Mascotas:Acuarios:Peces Accesorios',
  'terrarios y calefaccion': 'Mascotas:Acuarios:Reptiles Accesorios',
  'calefaccion': 'Mascotas:Acuarios:Reptiles Accesorios',
  'fitness y musculacion gym en casa': 'Deportes y Aire Libre:Fitness',
  'fitness': 'Deportes y Aire Libre:Fitness',
  'musculacion gym en casa': 'Deportes y Aire Libre:Fitness',
  'fitness y musculacion': 'Deportes y Aire Libre:Fitness',
  'maquinas de cardio': 'Deportes y Aire Libre:Fitness:Cardio',
  'pesas y fuerza': 'Deportes y Aire Libre:Fitness:Pesas',
  'pesas': 'Deportes y Aire Libre:Fitness:Pesas',
  'fuerza': 'Deportes y Aire Libre:Fitness:Pesas',
  'accesorios funcionales  crossfit': 'Deportes y Aire Libre:Fitness:Funcional',
  'ciclismo': 'Deportes y Aire Libre:Ciclismo',
  'bicicletas': 'Deportes y Aire Libre:Ciclismo:Bicicletas',
  'componentes y refacciones': 'Deportes y Aire Libre:Ciclismo:Componentes Bici',
  'componentes': 'Deportes y Aire Libre:Ciclismo:Componentes Bici',
  'refacciones': 'Deportes y Aire Libre:Ciclismo:Componentes Bici',
  'accesorios para ciclista': 'Deportes y Aire Libre:Ciclismo:Accesorios Bici',
  'deportes de equipo': 'Deportes y Aire Libre:Deportes Equipo',
  'futbol': 'Deportes y Aire Libre:Deportes Equipo:Futbol',
  'basquetbol': 'Deportes y Aire Libre:Deportes Equipo:Basket',
  'beisbol y softbol': 'Deportes y Aire Libre:Deportes Equipo:Beisbol',
  'beisbol': 'Deportes y Aire Libre:Deportes Equipo:Beisbol',
  'softbol': 'Deportes y Aire Libre:Deportes Equipo:Beisbol',
  'voleibol': 'Deportes y Aire Libre:Deportes Equipo:Voleibol',
  'futbol americano': 'Deportes y Aire Libre:Deportes Equipo:Fut Americano',
  'camping caza y pesca': 'Deportes y Aire Libre:Camping',
  'camping caza': 'Deportes y Aire Libre:Camping',
  'pesca': 'Deportes y Aire Libre:Camping',
  'camping': 'Deportes y Aire Libre:Camping',
  'caza y pesca': 'Deportes y Aire Libre:Camping',
  'camping y senderismo': 'Deportes y Aire Libre:Camping:Camping',
  'senderismo': 'Deportes y Aire Libre:Camping:Camping',
  'deportes de raqueta': 'Deportes y Aire Libre:Raqueta',
  'padel': 'Deportes y Aire Libre:Raqueta:Padel',
  'ping pong': 'Deportes y Aire Libre:Raqueta:Ping Pong',
  'squash  fronton': 'Deportes y Aire Libre:Raqueta:Squash',
  'deportes acuaticos': 'Deportes y Aire Libre:Acuaticos',
  'natacion': 'Deportes y Aire Libre:Acuaticos:Natacion',
  'surf y bodyboard': 'Deportes y Aire Libre:Acuaticos:Surf',
  'surf': 'Deportes y Aire Libre:Acuaticos:Surf',
  'bodyboard': 'Deportes y Aire Libre:Acuaticos:Surf',
  'buceo y snorkel': 'Deportes y Aire Libre:Acuaticos:Buceo',
  'buceo': 'Deportes y Aire Libre:Acuaticos:Buceo',
  'snorkel': 'Deportes y Aire Libre:Acuaticos:Buceo',
  'kayaks e inflables': 'Deportes y Aire Libre:Acuaticos:Kayaks',
  'patines skate y scooters': 'Deportes y Aire Libre:Patines',
  'patines skate': 'Deportes y Aire Libre:Patines',
  'scooters': 'Deportes y Aire Libre:Patines',
  'skate y scooters': 'Deportes y Aire Libre:Patines',
  'skateboarding': 'Deportes y Aire Libre:Patines:Skate',
  'proteccion': 'Deportes y Aire Libre:Patines:Proteccion Skate',
  'golf': 'Deportes y Aire Libre:Golf',
  'palos de golf': 'Deportes y Aire Libre:Golf:Palos',
  'bolsas de golf': 'Deportes y Aire Libre:Golf:Bolsas Golf',
  'pelotas y accesorios': 'Deportes y Aire Libre:Golf:Accesorios Golf',
  'pelotas': 'Deportes y Aire Libre:Golf:Accesorios Golf',
  'artes marciales y boxeo': 'Deportes y Aire Libre:Artes Marciales',
  'artes marciales': 'Deportes y Aire Libre:Artes Marciales',
  'boxeo': 'Deportes y Aire Libre:Artes Marciales',
  'artes marciales mma karate judo': 'Deportes y Aire Libre:Artes Marciales:MMA',
  'artes marciales mma': 'Deportes y Aire Libre:Artes Marciales:MMA',
  'karate': 'Deportes y Aire Libre:Artes Marciales:MMA',
  'judo': 'Deportes y Aire Libre:Artes Marciales:MMA',
  'refacciones autos y camionetas': 'Automotriz y Motocicletas:Refacciones Auto',
  'refacciones autos': 'Automotriz y Motocicletas:Refacciones Auto',
  'camionetas': 'Automotriz y Motocicletas:Refacciones Auto',
  'motor': 'Automotriz y Motocicletas:Refacciones Auto:Motor',
  'frenos': 'Automotriz y Motocicletas:Refacciones Auto:Frenos',
  'suspension y direccion': 'Automotriz y Motocicletas:Refacciones Auto:Suspension',
  'suspension': 'Automotriz y Motocicletas:Refacciones Auto:Suspension',
  'direccion': 'Automotriz y Motocicletas:Refacciones Auto:Suspension',
  'carroceria': 'Automotriz y Motocicletas:Refacciones Auto:Carroceria',
  'sistema electrico': 'Automotriz y Motocicletas:Refacciones Auto:Electrico',
  'transmision': 'Automotriz y Motocicletas:Refacciones Auto:Transmision',
  'accesorios para autos': 'Automotriz y Motocicletas:Accesorios Auto',
  'accesorios de interior': 'Automotriz y Motocicletas:Accesorios Auto:Interior',
  'accesorios de exterior': 'Automotriz y Motocicletas:Accesorios Auto:Exterior',
  'audio y electronica': 'Automotriz y Motocicletas:Accesorios Auto:Car Audio',
  'audio': 'Automotriz y Motocicletas:Accesorios Auto:Car Audio',
  'electronica': 'Automotriz y Motocicletas:Accesorios Auto:Car Audio',
  'llantas y rines': 'Automotriz y Motocicletas:Llantas',
  'llantas': 'Automotriz y Motocicletas:Llantas',
  'rines': 'Automotriz y Motocicletas:Llantas',
  'accesorios de llantas': 'Automotriz y Motocicletas:Llantas:Accesorios Llantas',
  'motociclismo': 'Automotriz y Motocicletas:Motos',
  'equipamiento para motociclista': 'Automotriz y Motocicletas:Motos:Equipamiento Moto',
  'refacciones para moto': 'Automotriz y Motocicletas:Motos:Refacciones Moto',
  'accesorios para moto': 'Automotriz y Motocicletas:Motos:Accesorios Moto',
  'herramientas y cuidado del vehiculo': 'Automotriz y Motocicletas:Herramientas Auto',
  'cuidado del vehiculo': 'Automotriz y Motocicletas:Herramientas Auto',
  'aceites y fluidos': 'Automotriz y Motocicletas:Herramientas Auto:Aceites',
  'aceites': 'Automotriz y Motocicletas:Herramientas Auto:Aceites',
  'fluidos': 'Automotriz y Motocicletas:Herramientas Auto:Aceites',
  'estetica automotriz': 'Automotriz y Motocicletas:Herramientas Auto:Detailing',
  'herramientas automotrices': 'Automotriz y Motocicletas:Herramientas Auto:Herramientas Mec',
  'despensa y abarrotes': 'Alimentos y Bebidas:Despensa',
  'despensa': 'Alimentos y Bebidas:Despensa',
  'abarrotes': 'Alimentos y Bebidas:Despensa',
  'arroz frijol y semillas': 'Alimentos y Bebidas:Despensa:Arroz y Granos',
  'arroz frijol': 'Alimentos y Bebidas:Despensa:Arroz y Granos',
  'arroz': 'Alimentos y Bebidas:Despensa:Arroz y Granos',
  'frijol y semillas': 'Alimentos y Bebidas:Despensa:Arroz y Granos',
  'pastas y salsas para pasta': 'Alimentos y Bebidas:Despensa:Pastas',
  'pastas': 'Alimentos y Bebidas:Despensa:Pastas',
  'salsas para pasta': 'Alimentos y Bebidas:Despensa:Pastas',
  'enlatados y conservas': 'Alimentos y Bebidas:Despensa:Enlatados',
  'enlatados': 'Alimentos y Bebidas:Despensa:Enlatados',
  'conservas': 'Alimentos y Bebidas:Despensa:Enlatados',
  'aceites y vinagres': 'Alimentos y Bebidas:Despensa:Aceites',
  'vinagres': 'Alimentos y Bebidas:Despensa:Aceites',
  'especias y condimentos': 'Alimentos y Bebidas:Despensa:Especias',
  'especias': 'Alimentos y Bebidas:Despensa:Especias',
  'condimentos': 'Alimentos y Bebidas:Despensa:Especias',
  'harinas y reposteria': 'Alimentos y Bebidas:Despensa:Harinas',
  'harinas': 'Alimentos y Bebidas:Despensa:Harinas',
  'reposteria': 'Alimentos y Bebidas:Despensa:Harinas',
  'sopas cremas y pures': 'Alimentos y Bebidas:Despensa:Sopas',
  'sopas cremas': 'Alimentos y Bebidas:Despensa:Sopas',
  'pures': 'Alimentos y Bebidas:Despensa:Sopas',
  'sopas': 'Alimentos y Bebidas:Despensa:Sopas',
  'cremas y pures': 'Alimentos y Bebidas:Despensa:Sopas',
  'comida instantanea': 'Alimentos y Bebidas:Despensa:Instantaneos',
  'salsas chiles y moles': 'Alimentos y Bebidas:Despensa:Salsas',
  'salsas chiles': 'Alimentos y Bebidas:Despensa:Salsas',
  'moles': 'Alimentos y Bebidas:Despensa:Salsas',
  'salsas': 'Alimentos y Bebidas:Despensa:Salsas',
  'chiles y moles': 'Alimentos y Bebidas:Despensa:Salsas',
  'mermeladas miel y untables': 'Alimentos y Bebidas:Despensa:Untables',
  'mermeladas miel': 'Alimentos y Bebidas:Despensa:Untables',
  'untables': 'Alimentos y Bebidas:Despensa:Untables',
  'mermeladas': 'Alimentos y Bebidas:Despensa:Untables',
  'miel y untables': 'Alimentos y Bebidas:Despensa:Untables',
  'mayonesas y aderezos': 'Alimentos y Bebidas:Despensa:Aderezos',
  'mayonesas': 'Alimentos y Bebidas:Despensa:Aderezos',
  'aderezos': 'Alimentos y Bebidas:Despensa:Aderezos',
  'desayuno y panaderia': 'Alimentos y Bebidas:Desayuno',
  'desayuno': 'Alimentos y Bebidas:Desayuno',
  'panaderia': 'Alimentos y Bebidas:Desayuno',
  'cereales y barras': 'Alimentos y Bebidas:Desayuno:Cereales',
  'cereales': 'Alimentos y Bebidas:Desayuno:Cereales',
  'barras': 'Alimentos y Bebidas:Desayuno:Cereales',
  'panaderia y galletas': 'Alimentos y Bebidas:Desayuno:Panaderia',
  'galletas': 'Alimentos y Bebidas:Desayuno:Panaderia',
  'untables mermeladas cremas': 'Alimentos y Bebidas:Desayuno:Untables',
  'untables mermeladas': 'Alimentos y Bebidas:Desayuno:Untables',
  'cremas': 'Alimentos y Bebidas:Desayuno:Untables',
  'bebidas sin alcohol': 'Alimentos y Bebidas:Bebidas',
  'bebidas': 'Alimentos y Bebidas:Bebidas',
  'aguas y refrescos': 'Alimentos y Bebidas:Bebidas:Aguas',
  'aguas': 'Alimentos y Bebidas:Bebidas:Aguas',
  'refrescos': 'Alimentos y Bebidas:Bebidas:Aguas',
  'jugos y nectares': 'Alimentos y Bebidas:Bebidas:Jugos',
  'jugos': 'Alimentos y Bebidas:Bebidas:Jugos',
  'nectares': 'Alimentos y Bebidas:Bebidas:Jugos',
  'cafe y te': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'cafe': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'energizantes e isotonicos': 'Alimentos y Bebidas:Bebidas:Energizantes',
  'vinos licores y cervezas': 'Alimentos y Bebidas:Vinos y Licores',
  'vinos licores': 'Alimentos y Bebidas:Vinos y Licores',
  'cervezas': 'Alimentos y Bebidas:Vinos y Licores',
  'vinos': 'Alimentos y Bebidas:Vinos y Licores',
  'licores y cervezas': 'Alimentos y Bebidas:Vinos y Licores',
  'tequila y mezcal': 'Alimentos y Bebidas:Vinos y Licores:Tequila y Mezcal',
  'cervezas artesanales y comerciales': 'Alimentos y Bebidas:Vinos y Licores:Cervezas',
  'cervezas artesanales': 'Alimentos y Bebidas:Vinos y Licores:Cervezas',
  'comerciales': 'Alimentos y Bebidas:Vinos y Licores:Cervezas',
  'vinos tinto blanco rosado': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'vinos tinto': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'blanco': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'rosado': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'whisky vodka y ginebra': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'whisky vodka': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'ginebra': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'vodka y ginebra': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'ron brandy y cognac': 'Alimentos y Bebidas:Vinos y Licores:Ron y Brandy',
  'ron brandy': 'Alimentos y Bebidas:Vinos y Licores:Ron y Brandy',
  'cognac': 'Alimentos y Bebidas:Vinos y Licores:Ron y Brandy',
  'ron': 'Alimentos y Bebidas:Vinos y Licores:Ron y Brandy',
  'brandy y cognac': 'Alimentos y Bebidas:Vinos y Licores:Ron y Brandy',
  'licores cremas y digestivos': 'Alimentos y Bebidas:Vinos y Licores:Licores y Cremas',
  'licores cremas': 'Alimentos y Bebidas:Vinos y Licores:Licores y Cremas',
  'digestivos': 'Alimentos y Bebidas:Vinos y Licores:Licores y Cremas',
  'licores': 'Alimentos y Bebidas:Vinos y Licores:Licores y Cremas',
  'cremas y digestivos': 'Alimentos y Bebidas:Vinos y Licores:Licores y Cremas',
  'mixers y cocteleria': 'Alimentos y Bebidas:Vinos y Licores:Mixers',
  'mixers': 'Alimentos y Bebidas:Vinos y Licores:Mixers',
  'cocteleria': 'Alimentos y Bebidas:Vinos y Licores:Mixers',
  'snacks y dulces': 'Alimentos y Bebidas:Snacks',
  'snacks': 'Alimentos y Bebidas:Snacks',
  'dulces': 'Alimentos y Bebidas:Snacks',
  'botanas saladas papas frituras': 'Alimentos y Bebidas:Snacks:Botanas',
  'botanas saladas papas': 'Alimentos y Bebidas:Snacks:Botanas',
  'frituras': 'Alimentos y Bebidas:Snacks:Botanas',
  'botanas saladas': 'Alimentos y Bebidas:Snacks:Botanas',
  'dulces y golosinas': 'Alimentos y Bebidas:Snacks:Dulces',
  'golosinas': 'Alimentos y Bebidas:Snacks:Dulces',
  'chocolates y bombones': 'Alimentos y Bebidas:Snacks:Chocolates',
  'chocolates': 'Alimentos y Bebidas:Snacks:Chocolates',
  'bombones': 'Alimentos y Bebidas:Snacks:Chocolates',
  'galletas y barquillos': 'Alimentos y Bebidas:Snacks:Galletas',
  'barquillos': 'Alimentos y Bebidas:Snacks:Galletas',
  'frutos secos y semillas': 'Alimentos y Bebidas:Snacks:Frutos Secos',
  'frutos secos': 'Alimentos y Bebidas:Snacks:Frutos Secos',
  'palomitas de maiz': 'Alimentos y Bebidas:Snacks:Palomitas',
  'gomitas y masmelos': 'Alimentos y Bebidas:Snacks:Gomitas',
  'gomitas': 'Alimentos y Bebidas:Snacks:Gomitas',
  'masmelos': 'Alimentos y Bebidas:Snacks:Gomitas',
  'chicles y pastillas': 'Alimentos y Bebidas:Snacks:Chicles',
  'chicles': 'Alimentos y Bebidas:Snacks:Chicles',
  'pastillas': 'Alimentos y Bebidas:Snacks:Chicles',
  'snacks saludables': 'Alimentos y Bebidas:Snacks:Snacks Saludables',
  'dulces tipicos mexicanos': 'Alimentos y Bebidas:Snacks:Dulces Tipicos',
  'mundo saludable': 'Alimentos y Bebidas:Saludable',
  'organico y superfoods': 'Alimentos y Bebidas:Saludable:Organico',
  'organico': 'Alimentos y Bebidas:Saludable:Organico',
  'superfoods': 'Alimentos y Bebidas:Saludable:Organico',
  'sin gluten gluten free': 'Alimentos y Bebidas:Saludable:Sin Gluten',
  'sin gluten': 'Alimentos y Bebidas:Saludable:Sin Gluten',
  'keto y low carb': 'Alimentos y Bebidas:Saludable:Keto',
  'keto': 'Alimentos y Bebidas:Saludable:Keto',
  'low carb': 'Alimentos y Bebidas:Saludable:Keto',
  'vegano y plantbased': 'Alimentos y Bebidas:Saludable:Vegano',
  'vegano': 'Alimentos y Bebidas:Saludable:Vegano',
  'plantbased': 'Alimentos y Bebidas:Saludable:Vegano',
  'adultos 18  bienestar sexual': 'Otros:Adultos',
  'adultos': 'Otros:Adultos',
  'juguetes eroticos': 'Otros:Adultos:Juguetes',
  'lenceria erotica y disfraces': 'Otros:Adultos:Lenceria',
  'disfraces': 'Otros:Adultos:Lenceria',
  'lubricantes y aceites': 'Otros:Adultos:Lubricantes',
  'lubricantes': 'Otros:Adultos:Lubricantes',
  'fetiche y bondage': 'Otros:Adultos:Fetiche',
  'fetiche': 'Otros:Adultos:Fetiche',
  'bondage': 'Otros:Adultos:Fetiche',
  'exclusivos tiendas oficiales': 'Otros:Restringidos',
  'guias prepagadas': 'Otros:Restringidos:Guias',
  'software y licencias': 'Otros:Restringidos:Software',
  'software': 'Otros:Restringidos:Software',
  'licencias': 'Otros:Restringidos:Software',
  'suscripciones digitales': 'Otros:Restringidos:Suscripciones',
};
