import { normalize } from './utils';

export const GENDER_KEYWORDS: Record<string, string> = {
  'mujer': 'Mujer',
  'dama': 'Mujer',
  'senora': 'Mujer',
  'hombre': 'Hombre',
  'caballero': 'Hombre',
  'nino': 'Niños, Niñas y Bebés',
  'nina': 'Niños, Niñas y Bebés',
  'infantil': 'Niños, Niñas y Bebés',
  'bebe': 'Niños, Niñas y Bebés',
};

// Map keywords to semantic category concepts
// Format: "Category:SubCategory:SubSubCategory" or "Category:SubCategory"
export const KEYWORD_CONCEPTS: Record<string, string> = {
  // --- MODA ROPA Y ACCESORIOS ---
  // Accesorios de Moda
  'reloj': 'Accesorios de Moda:Relojes:Analogicos',
  'smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'joyeria': 'Accesorios de Moda:Joyería:Fantasia',
  'collar': 'Accesorios de Moda:Joyería:Collares',
  'dije': 'Accesorios de Moda:Joyería:Collares',
  'arete': 'Accesorios de Moda:Joyería:Aretes',
  'broquel': 'Accesorios de Moda:Joyería:Aretes',
  'pulsera': 'Accesorios de Moda:Joyería:Pulseras',
  'brazalete': 'Accesorios de Moda:Joyería:Pulseras',
  'anillo': 'Accesorios de Moda:Joyería:Anillos',
  'lentes': 'Accesorios de Moda:Lentes:Sol',
  'gafas': 'Accesorios de Moda:Lentes:Sol',
  'lentes sol': 'Accesorios de Moda:Lentes:Sol',
  'gafas sol': 'Accesorios de Moda:Lentes:Sol',
  'lentes oftalmicos': 'Accesorios de Moda:Lentes:Oftalmicos',
  'armazon': 'Accesorios de Moda:Lentes:Oftalmicos',
  'equipaje': 'Accesorios de Moda:Equipaje:Maletas',
  'maleta': 'Accesorios de Moda:Equipaje:Maletas',
  'mochila': 'Accesorios de Moda:Equipaje:Mochilas',
  'backpack': 'Accesorios de Moda:Equipaje:Mochilas',
  'bolsa viaje': 'Accesorios de Moda:Equipaje:Bolsas Viaje',
  'cangurera': 'Accesorios de Moda:Equipaje:Cangureras',
  'cinturon': 'Accesorios de Moda:Varios:Cinturones',
  'gorra': 'Accesorios de Moda:Varios:Gorras',
  'sombrero': 'Accesorios de Moda:Varios:Gorras',
  'bufanda': 'Accesorios de Moda:Varios:Bufandas',
  'panuelo': 'Accesorios de Moda:Varios:Bufandas',
  'paraguas': 'Accesorios de Moda:Varios:Paraguas',

  // Mujer (Root Override handled in logic)
  'vestido': 'Mujer:Ropa:Vestidos',
  'blusa': 'Mujer:Ropa:Blusas y Tops',
  'top': 'Mujer:Ropa:Blusas y Tops',
  'falda': 'Mujer:Ropa:Faldas y Shorts',
  'short mujer': 'Mujer:Ropa:Faldas y Shorts',
  'abrigo mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'chamarra mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'sueter mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'sudadera mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'lenceria': 'Mujer:Ropa:Lencería y Ropa Interior',
  'calzon': 'Mujer:Ropa:Lencería y Ropa Interior',
  'brasier': 'Mujer:Ropa:Lencería y Ropa Interior',
  'traje bano mujer': 'Mujer:Ropa:Trajes de Baño',
  'bikini': 'Mujer:Ropa:Trajes de Baño',
  'ropa deportiva mujer': 'Mujer:Ropa:Ropa Deportiva',
  'leggins': 'Mujer:Ropa:Ropa Deportiva',
  'overol': 'Mujer:Ropa:Overoles y Jumpers',
  'jumper': 'Mujer:Ropa:Overoles y Jumpers',
  'pijama mujer': 'Mujer:Ropa:Pijamas',
  'bolsa mano': 'Mujer:Bolsas:Bolsas',
  'tote': 'Mujer:Bolsas:Bolsas',
  'crossbody': 'Mujer:Bolsas:Bolsas',
  'clutch': 'Mujer:Bolsas:Clutches',
  'cartera mujer': 'Mujer:Bolsas:Carteras',
  'tenis mujer': 'Mujer:Calzado:Tenis',
  'bota mujer': 'Mujer:Calzado:Botas',
  'botin mujer': 'Mujer:Calzado:Botas',
  'sandalia mujer': 'Mujer:Calzado:Sandalias',
  'zapatilla': 'Mujer:Calzado:Tacones',
  'tacon': 'Mujer:Calzado:Tacones',
  'flats': 'Mujer:Calzado:Flats',
  'balerina': 'Mujer:Calzado:Flats',

  // Hombre
  'playera': 'Hombre:Ropa:Playeras y Polos',
  'polo': 'Hombre:Ropa:Playeras y Polos',
  'camisa': 'Hombre:Ropa:Camisas',
  'pantalon hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'jeans hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'short hombre': 'Hombre:Ropa:Shorts y Bermudas',
  'bermuda': 'Hombre:Ropa:Shorts y Bermudas',
  'sudadera hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'sueter hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'chamarra hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'abrigo hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'chaleco hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'traje hombre': 'Hombre:Ropa:Trajes y Sacos',
  'saco': 'Hombre:Ropa:Trajes y Sacos',
  'boxer': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calzoncillo': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calcetin': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'traje bano hombre': 'Hombre:Ropa:Trajes de Baño',
  'ropa deportiva hombre': 'Hombre:Ropa:Ropa Deportiva',
  'tenis hombre': 'Hombre:Calzado:Tenis',
  'zapato vestir': 'Hombre:Calzado:Zapatos Vestir',
  'bota hombre': 'Hombre:Calzado:Botas',
  'sandalia hombre': 'Hombre:Calzado:Sandalias',
  'chancla': 'Hombre:Calzado:Sandalias',

  // Niños/Bebes
  'ropa bebe': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'pañalero': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'zapato bebe': 'Niños, Niñas y Bebés:Bebés:Zapatos Bebé',
  'babero': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'vestido nina': 'Niños, Niñas y Bebés:Niñas:Vestidos',
  'conjunto nina': 'Niños, Niñas y Bebés:Niñas:Conjuntos',
  'playera nina': 'Niños, Niñas y Bebés:Niñas:Playeras',
  'falda nina': 'Niños, Niñas y Bebés:Niñas:Faldas',
  'zapato nina': 'Niños, Niñas y Bebés:Niñas:Zapatos Niña',
  'conjunto nino': 'Niños, Niñas y Bebés:Niños:Conjuntos',
  'playera nino': 'Niños, Niñas y Bebés:Niños:Playeras',
  'pantalon nino': 'Niños, Niñas y Bebés:Niños:Pantalones',
  'sudadera nino': 'Niños, Niñas y Bebés:Niños:Sudaderas',
  'zapato nino': 'Niños, Niñas y Bebés:Niños:Zapatos Niño',

  // Ropa Especializada
  'disfraz': 'Ropa Especializada / Otros:Especializada:Disfraces y Cosplay',
  'cosplay': 'Ropa Especializada / Otros:Especializada:Disfraces y Cosplay',
  'bata medico': 'Ropa Especializada / Otros:Especializada:Ropa de Trabajo Industrial',
  'uniforme': 'Ropa Especializada / Otros:Especializada:Ropa de Trabajo Industrial',
  'maternidad': 'Ropa Especializada / Otros:Especializada:Ropa de Maternidad',
  'embarazada': 'Ropa Especializada / Otros:Especializada:Ropa de Maternidad',
  'talla extra': 'Ropa Especializada / Otros:Especializada:Tallas Extra (Plus Size)',
  'plus size': 'Ropa Especializada / Otros:Especializada:Tallas Extra (Plus Size)',

  // --- ELECTRONICA Y TECNOLOGIA ---
  // Celulares
  'celular': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'smartphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'samsung galaxy': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'celular basico': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celular reacondicionado': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares Reacondicionados',
  'funda celular': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'carcasa celular': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'protector pantalla': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'mica': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'cargador celular': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cable usb': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'power bank': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'bateria externa': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'soporte celular': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'smartband': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'correa smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',

  // Computacion
  'laptop': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'macbook': 'Electrónica y Tecnología:Computación:MacBooks',
  'notebook': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop gamer': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'ultrabook': 'Electrónica y Tecnología:Computación:Ultrabooks',
  'all in one': 'Electrónica y Tecnología:Computación:All-in-One',
  'computadora escritorio': 'Electrónica y Tecnología:Computación:All-in-One',
  'pc gamer': 'Electrónica y Tecnología:Computación:PC Gamer',
  'mini pc': 'Electrónica y Tecnología:Computación:Mini PCs',
  'disco duro': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'ssd': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'memoria ram': 'Electrónica y Tecnología:Computación:Memorias RAM',
  'procesador': 'Electrónica y Tecnología:Computación:Procesadores',
  'cpu': 'Electrónica y Tecnología:Computación:Procesadores',
  'tarjeta video': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'gpu': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'motherboard': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'tarjeta madre': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'fuente poder': 'Electrónica y Tecnología:Computación:Fuentes de Poder',
  'gabinete pc': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'monitor': 'Electrónica y Tecnología:Computación:Monitores',
  'teclado': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'mouse': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'raton': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'webcam': 'Electrónica y Tecnología:Computación:Webcams',
  'hub usb': 'Electrónica y Tecnología:Computación:Hubs USB y Adaptadores',
  'disco duro externo': 'Electrónica y Tecnología:Computación:Almacenamiento Externo',
  'memoria usb': 'Electrónica y Tecnología:Computación:Memorias USB',
  'pendrive': 'Electrónica y Tecnología:Computación:Memorias USB',
  'micro sd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'sd card': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'router': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'modem': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'repetidor wifi': 'Electrónica y Tecnología:Computación:Repetidores de Señal',
  'cable ethernet': 'Electrónica y Tecnología:Computación:Cables de Red',

  // TV Audio Video
  'smart tv': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'televisor': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'pantalla': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'soporte tv': 'Electrónica y Tecnología:TV, Audio y Video:Soportes para TV',
  'roku': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'chromecast': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'fire tv': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'audifonos': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'auriculares': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'bocina': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'parlante': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'barra sonido': 'Electrónica y Tecnología:TV, Audio y Video:Barras de Sonido',
  'home theater': 'Electrónica y Tecnología:TV, Audio y Video:Home Theater',
  'alexa': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'google home': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'proyector': 'Electrónica y Tecnología:TV, Audio y Video:Proyectores',

  // Camaras
  'camara dslr': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camara reflex': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camara mirrorless': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Mirrorless',
  'gopro': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camara accion': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'camara instantanea': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'instax': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'drone': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'dron': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'lente camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Objetivos',
  'tripie': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',
  'aro luz': 'Electrónica y Tecnología:Cámaras y Fotografía:Iluminación de Estudio',
  'mochila camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Mochilas y Estuches',

  // Videojuegos
  'ps5': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'ps4': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'playstation': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'xbox': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'xbox series': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'nintendo switch': 'Electrónica y Tecnología:Videojuegos:Nintendo',
  'consola retro': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'videojuego': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego ps4': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego xbox': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'juego switch': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'tarjeta regalo': 'Electrónica y Tecnología:Videojuegos:Tarjetas de Regalo',
  'control ps4': 'Electrónica y Tecnología:Videojuegos:Controles',
  'control xbox': 'Electrónica y Tecnología:Videojuegos:Controles',
  'joycon': 'Electrónica y Tecnología:Videojuegos:Controles',
  'headset gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'audifonos gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'silla gamer': 'Electrónica y Tecnología:Videojuegos:Sillas Gamer',
  'volante gamer': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',

  // Oficina
  'impresora': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras',
  'multifuncional': 'Electrónica y Tecnología:Electrónica de Oficina:Multifuncionales',
  'escaner': 'Electrónica y Tecnología:Electrónica de Oficina:Escáneres',
  'impresora 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras 3D',
  'cartucho tinta': 'Electrónica y Tecnología:Electrónica de Oficina:Cartuchos de Tinta',
  'toner': 'Electrónica y Tecnología:Electrónica de Oficina:Tóners',
  'filamento 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Filamentos 3D',
  'calculadora': 'Electrónica y Tecnología:Electrónica de Oficina:Calculadoras',
  'trituradora': 'Electrónica y Tecnología:Electrónica de Oficina:Trituradoras',
  'telefono fijo': 'Electrónica y Tecnología:Electrónica de Oficina:Teléfonos Fijos',

  // --- HOGAR, JARDIN Y HERRAMIENTAS ---
  // Muebles
  'sofa': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sillon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'mesa centro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'mueble tv': 'Hogar, Jardín y Herramientas:Muebles y Organización:Muebles TV',
  'puff': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'cama': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'base cama': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'colchon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Colchones',
  'cabecera': 'Hogar, Jardín y Herramientas:Muebles y Organización:Cabeceras',
  'buro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'comoda': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'armario': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'ropero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'closet': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Juegos de Comedor',
  'mesa': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'silla': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'bufetera': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bufeteras',
  'banco barra': 'Hogar, Jardín y Herramientas:Muebles y Organización:Bancos Barra',
  'escritorio': 'Hogar, Jardín y Herramientas:Muebles y Organización:Escritorios',
  'silla oficina': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sillas Oficina',
  'archivero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'librero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',

  // Cocina
  'olla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'cacerola': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'sarten': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'wok': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'olla presion': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas Presión',
  'molde hornear': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Moldes Hornear',
  'vajilla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'plato': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'vaso': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'copa': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'cubiertos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cubiertos',
  'mantel': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'servilleta tela': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Servilletas Manteles',
  'cuchillo cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tabla picar': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tupper': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'organizador cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Organizadores Cocina',
  'termo': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'cafetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cafeteras',
  'tetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',

  // Decoracion
  'lampara techo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Techo',
  'lampara mesa': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Mesa',
  'foco': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'tira led': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Tiras LED',
  'espejo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Espejos',
  'cuadro': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'reloj pared': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Relojes Pared',
  'vinilo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'cortina': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'persiana': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'alfombra': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'cojin': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cojines',
  'difusor aroma': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Difusores',
  'vela': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',

  // Cama y Baño
  'sabana': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Sábanas',
  'edredon': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'almohada': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'toalla': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Toallas',
  'cortina bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cortinas Baño',
  'tapete bano': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tapetes Baño',
  'cesto ropa': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cestos',
  'tendedero': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'tabla planchar': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tablas Planchar',
  'escoba': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Artículos Limpieza',
  'trapeador': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Artículos Limpieza',

  // Jardin
  'sala exterior': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Salas Exterior',
  'hamaca': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'sombrilla jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'asador carbon': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Carbón',
  'asador gas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Gas',
  'ahumador': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Ahumadores',
  'maceta': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'planta': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Plantas',
  'fertilizante': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sustratos',
  'semillas': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Semillas',
  'manguera': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'cortadora cesped': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Cortadoras',
  'desbrozadora': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Desbrozadoras',
  'motosierra': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Motosierras',
  'alberca': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Albercas',
  'inflable': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Inflables Agua',

  // Herramientas
  'taladro': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'esmeriladora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Esmeriladoras',
  'sierra': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Sierras',
  'lijadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Lijadoras',
  'soldadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Soldadoras',
  'compresor': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Compresores',
  'kit herramientas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Kits Herramientas',
  'desarmador': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'martillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'alicate': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'pinza': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'cinta metrica': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Medición',
  'tornillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'pegamento': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cerradura': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'grifo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Grifería',
  'regadera': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'bomba agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Bombas Agua',
  'boiler': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'extension electrica': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'interruptor': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'cable electrico': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cableado',
  'zapato seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Zapatos Seguridad',
  'casco seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cascos Lentes',
  'chaleco seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Chalecos',

  // --- BELLEZA Y SALUD ---
  'skincare': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'crema facial': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'maquillaje': 'Belleza y Salud:Maquillaje:Rostro',
  'base maquillaje': 'Belleza y Salud:Maquillaje:Rostro',
  'labial': 'Belleza y Salud:Maquillaje:Labios',
  'sombras ojos': 'Belleza y Salud:Maquillaje:Ojos',
  'shampoo': 'Belleza y Salud:Cuidado del Cabello:Shampoo y Acondicionador',
  'acondicionador': 'Belleza y Salud:Cuidado del Cabello:Shampoo y Acondicionador',
  'perfume': 'Belleza y Salud:Perfumes y Fragancias:Mujer',
  'locion': 'Belleza y Salud:Perfumes y Fragancias:Hombre',
  'fragancia': 'Belleza y Salud:Perfumes y Fragancias:Unisex',
  'rasuradora': 'Belleza y Salud:Cuidado Personal:Rasuradoras y Depiladoras',
  'depiladora': 'Belleza y Salud:Cuidado Personal:Rasuradoras y Depiladoras',
  'secadora cabello': 'Belleza y Salud:Cuidado Personal:Secadoras y Alaciadoras',
  'alaciadora': 'Belleza y Salud:Cuidado Personal:Secadoras y Alaciadoras',

  // --- ALIMENTOS Y BEBIDAS ---
  'cerveza': 'Alimentos y Bebidas:Vinos y Licores:Cervezas',
  'tequila': 'Alimentos y Bebidas:Vinos y Licores:Tequila y Mezcal',
  'mezcal': 'Alimentos y Bebidas:Vinos y Licores:Tequila y Mezcal',
  'vino tinto': 'Alimentos y Bebidas:Vinos y Licores:Vinos',
  'whisky': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'vodka': 'Alimentos y Bebidas:Vinos y Licores:Whisky y Vodka',
  'cafe grano': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'cafe molido': 'Alimentos y Bebidas:Bebidas:Cafe y Te',
  'chocolate': 'Alimentos y Bebidas:Snacks:Chocolates',
  'dulce': 'Alimentos y Bebidas:Snacks:Dulces',
  'botana': 'Alimentos y Bebidas:Snacks:Botanas',
  'aceite cocina': 'Alimentos y Bebidas:Despensa:Aceites',
  'proteina': 'Alimentos y Bebidas:Saludable:Organico', // Approx
  'vitamina': 'Belleza y Salud:Salud:Vitaminas', // Better match in Health
  'creatina': 'Belleza y Salud:Salud:Vitaminas', // Better match in Health

  // --- DEPORTES Y FITNESS ---
  'mancuerna': 'Deportes y Aire Libre:Fitness:Pesas',
  'pesa': 'Deportes y Aire Libre:Fitness:Pesas',
  'barra gimnasio': 'Deportes y Aire Libre:Fitness:Pesas',
  'caminadora': 'Deportes y Aire Libre:Fitness:Cardio',
  'eliptica': 'Deportes y Aire Libre:Fitness:Cardio',
  'bicicleta': 'Deportes y Aire Libre:Ciclismo:Bicicletas',
  'casco bicicleta': 'Deportes y Aire Libre:Ciclismo:Accesorios Bici',
  'balon futbol': 'Deportes y Aire Libre:Deportes Equipo:Futbol',
  'balon basket': 'Deportes y Aire Libre:Deportes Equipo:Basket',
  'casa campaña': 'Deportes y Aire Libre:Camping:Camping',
  'tienda campaña': 'Deportes y Aire Libre:Camping:Camping',
  'caña pescar': 'Deportes y Aire Libre:Camping:Pesca',
  'raqueta': 'Deportes y Aire Libre:Raqueta:Tenis',
  'goggles': 'Deportes y Aire Libre:Acuaticos:Natacion',
  'patines': 'Deportes y Aire Libre:Patines:Patines',
  'skate': 'Deportes y Aire Libre:Patines:Skate',
  'guantes box': 'Deportes y Aire Libre:Artes Marciales:Boxeo',
  'costal box': 'Deportes y Aire Libre:Artes Marciales:Boxeo',

  // --- MASCOTAS ---
  'croquetas perro': 'Mascotas:Perros:Alimento',
  'alimento perro': 'Mascotas:Perros:Alimento',
  'juguete perro': 'Mascotas:Perros:Juguetes',
  'cama perro': 'Mascotas:Perros:Camas',
  'correa perro': 'Mascotas:Perros:Paseo',
  'collar perro': 'Mascotas:Perros:Paseo',
  'shampoo perro': 'Mascotas:Perros:Higiene',
  'croquetas gato': 'Mascotas:Gatos:Alimento Gato',
  'alimento gato': 'Mascotas:Gatos:Alimento Gato',
  'arena gato': 'Mascotas:Gatos:Arena',
  'rascador gato': 'Mascotas:Gatos:Muebles Gato',
  'juguete gato': 'Mascotas:Gatos:Juguetes Gato',
  'pecera': 'Mascotas:Acuarios:Peces Accesorios',
  'acuario': 'Mascotas:Acuarios:Peces Accesorios',

  // --- AUTOMOTRIZ ---
  'llanta': 'Automotriz y Motocicletas:Llantas:Llantas',
  'rin': 'Automotriz y Motocicletas:Llantas:Rines',
  'bateria auto': 'Automotriz y Motocicletas:Refacciones Auto:Electrico',
  'aceite motor': 'Automotriz y Motocicletas:Herramientas Auto:Aceites',
  'casco moto': 'Automotriz y Motocicletas:Motos:Equipamiento Moto',
  'faro': 'Automotriz y Motocicletas:Refacciones Auto:Electrico',
  'bujia': 'Automotriz y Motocicletas:Refacciones Auto:Motor',
  'amortiguador': 'Automotriz y Motocicletas:Refacciones Auto:Suspension',
  'balata': 'Automotriz y Motocicletas:Refacciones Auto:Frenos',

  // --- INDUSTRIA Y EMPRESAS ---
  'caja carton': 'Industria y Empresas:Embalaje:Material Empaque',
  'cinta canela': 'Industria y Empresas:Embalaje:Material Empaque',
  'playo': 'Industria y Empresas:Embalaje:Material Empaque',
  'burbuja': 'Industria y Empresas:Embalaje:Material Empaque',
  'impresora tickets': 'Industria y Empresas:Comercial:POS',
  'lector codigos': 'Industria y Empresas:Comercial:POS',
  'maniqui': 'Industria y Empresas:Comercial:Exhibicion',
  'papel higienico industrial': 'Industria y Empresas:Limpieza:Papel Inst',

  // --- ENTRETENIMIENTO Y CULTURA ---
  'libro': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'novela': 'Entretenimiento, Arte y Cultura:Libros:Literatura',
  'comic': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'manga': 'Entretenimiento, Arte y Cultura:Libros:Comics',
  'guitarra': 'Entretenimiento, Arte y Cultura:Instrumentos:Guitarras',
  'piano': 'Entretenimiento, Arte y Cultura:Instrumentos:Teclados',
  'bateria musical': 'Entretenimiento, Arte y Cultura:Instrumentos:Baterias',
  'vinilo musica': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Vinilos',
  'disco vinilo': 'Entretenimiento, Arte y Cultura:Musica y Peliculas:Vinilos',

  // --- OTROS ---
  'juguete sexual': 'Otros:Adultos:Juguetes',
  'vibrador': 'Otros:Adultos:Juguetes',
  'lenceria erotica': 'Otros:Adultos:Lenceria',
  'antivirus': 'Otros:Restringidos:Software',
  'office': 'Otros:Restringidos:Software',
  'windows': 'Otros:Restringidos:Software',
  'tarjeta regalo digital': 'Otros:Restringidos:Suscripciones',
  
  // --- USER REQUESTED & MISSING ---
  'caja de carton': 'Industria y Empresas:Embalaje:Material Empaque',
  'celulares': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'consola': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'videojuegos': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'calzado': 'Mujer:Calzado', // Generic fallback
  'calzado mujer': 'Mujer:Calzado',
  'calzado hombre': 'Hombre:Calzado',
   'lipstick': 'Belleza y Salud:Maquillaje:Labios',
  'refresco': 'Alimentos y Bebidas:Bebidas:Aguas y Refrescos',
  'perfume hombre': 'Belleza y Salud:Perfumes:Hombre',
  'perfume mujer': 'Belleza y Salud:Perfumes:Mujer',
};
