import { normalize } from './utils';

export const GENDER_KEYWORDS: Record<string, string> = {
  'mujer': 'Mujer',
  'dama': 'Mujer',
  'senora': 'Mujer',
  'femenina': 'Mujer',
  'woman': 'Mujer',
  'ladies': 'Mujer',
  'chica': 'Mujer',
  'hombre': 'Hombre',
  'caballero': 'Hombre',
  'masculino': 'Hombre',
  'man': 'Hombre',
  'men': 'Hombre',
  'chico': 'Hombre',
  'nino': 'Niños, Niñas y Bebés',
  'nina': 'Niños, Niñas y Bebés',
  'infantil': 'Niños, Niñas y Bebés',
  'bebe': 'Niños, Niñas y Bebés',
  'kids': 'Niños, Niñas y Bebés',
  'baby': 'Niños, Niñas y Bebés',
  'toddler': 'Niños, Niñas y Bebés',
  'recien nacido': 'Niños, Niñas y Bebés',
  'newborn': 'Niños, Niñas y Bebés',
  'unisex': 'Unisex' 
};

// Map keywords to semantic category concepts
// Format: "RootID:CategoryID:SubCategoryID"
export const KEYWORD_CONCEPTS: Record<string, string> = {
  // ==========================================================================================
  // ELECTRÓNICA Y TECNOLOGÍA
  // ==========================================================================================

  // --- CELULARES Y TELEFONÍA ---
  // Smartphones
  'iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'apple iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone 15': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone 14': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone 13': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone 12': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone 11': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone x': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'iphone se': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'samsung galaxy': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy s24': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy s23': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy s22': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy a54': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy a34': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy z fold': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'galaxy z flip': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'xiaomi': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'redmi note': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'poco x5': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'poco f5': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'motorola': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'moto g': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'moto edge': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'huawei p60': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'huawei nova': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'honor': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'honor magic': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'oppo reno': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'vivo': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'realme': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'google pixel': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'oneplus': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'infinix': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'celular': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'smartphone': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'movil': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',
  'telefono': 'Electrónica y Tecnología:Celulares y Telefonía:Smartphones',

  // Celulares Básicos
  'nokia 105': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celular basico': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'celular teclas': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'feature phone': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',
  'cacahuate': 'Electrónica y Tecnología:Celulares y Telefonía:Celulares básicos',

  // Accesorios
  'funda iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'case samsung': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'carcasa': 'Electrónica y Tecnología:Celulares y Telefonía:Fundas y Carcasas',
  'protector pantalla': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'mica hidrogel': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'cristal templado': 'Electrónica y Tecnología:Celulares y Telefonía:Micas y Protectores',
  'cargador iphone': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cable usb c': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cable lightning': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'cubo carga rapida': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'power bank': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'bateria portatil': 'Electrónica y Tecnología:Celulares y Telefonía:Power Banks',
  'magsafe': 'Electrónica y Tecnología:Celulares y Telefonía:Cargadores y Cables',
  'soporte celular auto': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',
  'pop socket': 'Electrónica y Tecnología:Celulares y Telefonía:Soportes',

  // Wearables
  'apple watch ultra': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'apple watch series': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'galaxy watch': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'huawei watch gt': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'smartwatch': 'Electrónica y Tecnología:Celulares y Telefonía:Relojes Inteligentes',
  'xiaomi band': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'smartband': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'fitbit': 'Electrónica y Tecnología:Celulares y Telefonía:Pulseras de Actividad',
  'correa apple watch': 'Electrónica y Tecnología:Celulares y Telefonía:Correas y Cargadores Smartwatch',

  // --- COMPUTACIÓN ---
  // Laptops
  'macbook air': 'Electrónica y Tecnología:Computación:MacBooks',
  'macbook pro': 'Electrónica y Tecnología:Computación:MacBooks',
  'laptop hp': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop dell': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop lenovo': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop asus': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop acer': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'chromebook': 'Electrónica y Tecnología:Computación:Laptops Tradicionales',
  'laptop gamer': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'asus rog': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'asus tuf': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'msi katana': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'alienware': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'acer nitro': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'lenovo legion': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'hp omen': 'Electrónica y Tecnología:Computación:Laptops Gamer',
  'surface pro': 'Electrónica y Tecnología:Computación:Ultrabooks',
  
  // PC & Componentes
  'pc gamer': 'Electrónica y Tecnología:Computación:PC Gamer',
  'computadora escritorio': 'Electrónica y Tecnología:Computación:All-in-One',
  'imac': 'Electrónica y Tecnología:Computación:All-in-One',
  'mac mini': 'Electrónica y Tecnología:Computación:Mini PCs',
  'tarjeta de video': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'rtx 4090': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'rtx 4060': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'rx 7800': 'Electrónica y Tecnología:Computación:Tarjetas de Video',
  'procesador ryzen': 'Electrónica y Tecnología:Computación:Procesadores',
  'intel core i7': 'Electrónica y Tecnología:Computación:Procesadores',
  'intel core i5': 'Electrónica y Tecnología:Computación:Procesadores',
  'motherboard': 'Electrónica y Tecnología:Computación:Tarjetas Madre',
  'memoria ram ddr4': 'Electrónica y Tecnología:Computación:Memorias RAM',
  'memoria ram ddr5': 'Electrónica y Tecnología:Computación:Memorias RAM',
  'ssd nvme': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'disco duro': 'Electrónica y Tecnología:Computación:Discos Duros y SSD',
  'fuente de poder': 'Electrónica y Tecnología:Computación:Fuentes de Poder',
  'gabinete gamer': 'Electrónica y Tecnología:Computación:Gabinetes y Enfriamiento',
  'monitor gamer': 'Electrónica y Tecnología:Computación:Monitores',
  'monitor 144hz': 'Electrónica y Tecnología:Computación:Monitores',
  'teclado mecanico': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'mouse gamer': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'logitech g': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'razer': 'Electrónica y Tecnología:Computación:Teclados y Mouses',
  'webcam': 'Electrónica y Tecnología:Computación:Webcams',
  'disco duro externo': 'Electrónica y Tecnología:Computación:Almacenamiento Externo',
  'usb': 'Electrónica y Tecnología:Computación:Memorias USB',
  'micro sd': 'Electrónica y Tecnología:Computación:Tarjetas de Memoria',
  'router wifi': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'starlink': 'Electrónica y Tecnología:Computación:Routers y Módems',
  'repetidor wifi': 'Electrónica y Tecnología:Computación:Repetidores de Señal',
  'cable ethernet': 'Electrónica y Tecnología:Computación:Cables de Red',

  // Oficina
  'impresora epson': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras',
  'impresora hp': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras',
  'multifuncional': 'Electrónica y Tecnología:Electrónica de Oficina:Multifuncionales',
  'toner': 'Electrónica y Tecnología:Electrónica de Oficina:Tóners',
  'cartucho tinta': 'Electrónica y Tecnología:Electrónica de Oficina:Cartuchos de Tinta',
  'impresora 3d': 'Electrónica y Tecnología:Electrónica de Oficina:Impresoras 3D',
  'calculadora cientifica': 'Electrónica y Tecnología:Electrónica de Oficina:Calculadoras',
  
  // --- TV, AUDIO Y VIDEO ---
  'smart tv samsung': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'smart tv lg': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'pantalla 4k': 'Electrónica y Tecnología:TV, Audio y Video:Smart TVs',
  'roku express': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'chromecast': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'fire tv stick': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'apple tv': 'Electrónica y Tecnología:TV, Audio y Video:Dispositivos de Streaming',
  'soporte tv': 'Electrónica y Tecnología:TV, Audio y Video:Soportes para TV',
  'audifonos bluetooth': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'airpods pro': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'galaxy buds': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'sony wh1000xm': 'Electrónica y Tecnología:TV, Audio y Video:Audífonos',
  'bocina jbl': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'bocina bose': 'Electrónica y Tecnología:TV, Audio y Video:Bocinas Portátiles',
  'alexa echo': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'google nest': 'Electrónica y Tecnología:TV, Audio y Video:Asistentes de Voz',
  'barra de sonido': 'Electrónica y Tecnología:TV, Audio y Video:Barras de Sonido',
  'home theater': 'Electrónica y Tecnología:TV, Audio y Video:Home Theater',
  'proyector': 'Electrónica y Tecnología:TV, Audio y Video:Proyectores',

  // --- CÁMARAS ---
  'camara canon': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'camara nikon': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras DSLR',
  'sony alpha': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Mirrorless',
  'gopro hero': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras de Acción',
  'instax mini': 'Electrónica y Tecnología:Cámaras y Fotografía:Cámaras Instantáneas',
  'drone dji': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'mavic mini': 'Electrónica y Tecnología:Cámaras y Fotografía:Drones con cámara',
  'lente canon': 'Electrónica y Tecnología:Cámaras y Fotografía:Objetivos',
  'aro de luz': 'Electrónica y Tecnología:Cámaras y Fotografía:Iluminación de Estudio',
  'tripie camara': 'Electrónica y Tecnología:Cámaras y Fotografía:Tripiés y Estabilizadores',

  // --- VIDEOJUEGOS ---
  'ps5': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'playstation 5': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'ps4': 'Electrónica y Tecnología:Videojuegos:PlayStation',
  'xbox series x': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'xbox series s': 'Electrónica y Tecnología:Videojuegos:Xbox',
  'nintendo switch': 'Electrónica y Tecnología:Videojuegos:Nintendo',
  'switch oled': 'Electrónica y Tecnología:Videojuegos:Nintendo',
  'gameboy': 'Electrónica y Tecnología:Videojuegos:Consolas Retro',
  'mario bros': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'zelda': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'fifa 24': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'call of duty': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'gta v': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'minecraft': 'Electrónica y Tecnología:Videojuegos:Juegos Físicos',
  'tarjeta psn': 'Electrónica y Tecnología:Videojuegos:Tarjetas de Regalo',
  'tarjeta xbox': 'Electrónica y Tecnología:Videojuegos:Tarjetas de Regalo',
  'control ps5': 'Electrónica y Tecnología:Videojuegos:Controles',
  'control xbox': 'Electrónica y Tecnología:Videojuegos:Controles',
  'joy con': 'Electrónica y Tecnología:Videojuegos:Controles',
  'audifonos gamer': 'Electrónica y Tecnología:Videojuegos:Headsets Gamer',
  'silla gamer': 'Electrónica y Tecnología:Videojuegos:Sillas Gamer',
  'volante logitech': 'Electrónica y Tecnología:Videojuegos:Volantes y Pedales',

  // ==========================================================================================
  // MODA, ROPA Y CALZADO
  // ==========================================================================================
  
  // ROPA MUJER (Default)
  'vestido': 'Mujer:Ropa:Vestidos',
  'vestido de noche': 'Mujer:Ropa:Vestidos',
  'vestido casual': 'Mujer:Ropa:Vestidos',
  'maxi vestido': 'Mujer:Ropa:Vestidos',
  'blusa': 'Mujer:Ropa:Blusas y Tops',
  'top': 'Mujer:Ropa:Blusas y Tops',
  'crop top': 'Mujer:Ropa:Blusas y Tops',
  'camisa mujer': 'Mujer:Ropa:Blusas y Tops',
  'jeans mujer': 'Mujer:Ropa:Pantalones y Jeans',
  'pantalones mujer': 'Mujer:Ropa:Pantalones y Jeans',
  'leggings': 'Mujer:Ropa:Pantalones y Jeans',
  'joggers mujer': 'Mujer:Ropa:Pantalones y Jeans',
  'falda': 'Mujer:Ropa:Faldas y Shorts',
  'minifalda': 'Mujer:Ropa:Faldas y Shorts',
  'short mujer': 'Mujer:Ropa:Faldas y Shorts',
  'chamarra mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'abrigo mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'saco mujer': 'Mujer:Ropa:Abrigos y Chamarras',
  'gabardina': 'Mujer:Ropa:Abrigos y Chamarras',
  'sueter mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'sudadera mujer': 'Mujer:Ropa:Suéteres y Sudaderas',
  'cardigan': 'Mujer:Ropa:Suéteres y Sudaderas',
  'lenceria': 'Mujer:Ropa:Lencería y Ropa Interior',
  'brasier': 'Mujer:Ropa:Lencería y Ropa Interior',
  'calzones': 'Mujer:Ropa:Lencería y Ropa Interior',
  'traje de baño mujer': 'Mujer:Ropa:Trajes de Baño',
  'bikini': 'Mujer:Ropa:Trajes de Baño',
  'ropa deportiva mujer': 'Mujer:Ropa:Ropa Deportiva',
  'leggins deportivos': 'Mujer:Ropa:Ropa Deportiva',
  'overol': 'Mujer:Ropa:Overoles y Jumpers',
  'jumper': 'Mujer:Ropa:Overoles y Jumpers',
  'pijama mujer': 'Mujer:Ropa:Pijamas',

  // CALZADO MUJER
  'tenis mujer': 'Mujer:Calzado:Tenis',
  'sneakers mujer': 'Mujer:Calzado:Tenis',
  'tenis nike mujer': 'Mujer:Calzado:Tenis',
  'botas mujer': 'Mujer:Calzado:Botas',
  'botines mujer': 'Mujer:Calzado:Botas',
  'botas largas': 'Mujer:Calzado:Botas',
  'sandalias mujer': 'Mujer:Calzado:Sandalias',
  'huaraches mujer': 'Mujer:Calzado:Sandalias',
  'alpargatas': 'Mujer:Calzado:Sandalias',
  'tacones': 'Mujer:Calzado:Tacones',
  'zapatillas': 'Mujer:Calzado:Tacones',
  'flats': 'Mujer:Calzado:Flats',
  'balerinas': 'Mujer:Calzado:Flats',
  'mocasines mujer': 'Mujer:Calzado:Flats',

  // BOLSAS
  'bolsa': 'Mujer:Bolsas:Bolsas',
  'bolso': 'Mujer:Bolsas:Bolsas',
  'bolsa michael kors': 'Mujer:Bolsas:Bolsas',
  'bolsa coach': 'Mujer:Bolsas:Bolsas',
  'crossbody': 'Mujer:Bolsas:Bolsas',
  'mochila mujer': 'Mujer:Bolsas:Mochilas',
  'cartera mujer': 'Mujer:Bolsas:Carteras',
  'monedero': 'Mujer:Bolsas:Carteras',
  'clutch': 'Mujer:Bolsas:Clutches',
  'bolsa de fiesta': 'Mujer:Bolsas:Clutches',

  // ROPA HOMBRE
  'playera': 'Hombre:Ropa:Playeras y Polos',
  'playera polo': 'Hombre:Ropa:Playeras y Polos',
  'tshirt': 'Hombre:Ropa:Playeras y Polos',
  'camisa hombre': 'Hombre:Ropa:Camisas',
  'camisa vestir': 'Hombre:Ropa:Camisas',
  'camisa manga larga': 'Hombre:Ropa:Camisas',
  'jeans hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'pantalones hombre': 'Hombre:Ropa:Pantalones y Jeans',
  'levis': 'Hombre:Ropa:Pantalones y Jeans',
  'shorts hombre': 'Hombre:Ropa:Shorts y Bermudas',
  'bermudas': 'Hombre:Ropa:Shorts y Bermudas',
  'sudadera hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'hoodie': 'Hombre:Ropa:Sudaderas y Suéteres',
  'sueter hombre': 'Hombre:Ropa:Sudaderas y Suéteres',
  'chamarra hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'chaleco hombre': 'Hombre:Ropa:Chamarras y Abrigos',
  'traje hombre': 'Hombre:Ropa:Trajes y Sacos',
  'saco hombre': 'Hombre:Ropa:Trajes y Sacos',
  'blazer hombre': 'Hombre:Ropa:Trajes y Sacos',
  'boxers': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calzoncillos': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'calcetines': 'Hombre:Ropa:Ropa Interior y Calcetas',
  'traje de baño hombre': 'Hombre:Ropa:Trajes de Baño',
  'ropa deportiva hombre': 'Hombre:Ropa:Ropa Deportiva',
  'pants hombre': 'Hombre:Ropa:Ropa Deportiva',

  // CALZADO HOMBRE
  'tenis hombre': 'Hombre:Calzado:Tenis',
  'sneakers hombre': 'Hombre:Calzado:Tenis',
  'jordan': 'Hombre:Calzado:Tenis',
  'yeezy': 'Hombre:Calzado:Tenis',
  'zapatos vestir hombre': 'Hombre:Calzado:Zapatos Vestir',
  'zapatos oxford': 'Hombre:Calzado:Zapatos Vestir',
  'botas hombre': 'Hombre:Calzado:Botas',
  'botas trabajo': 'Hombre:Calzado:Botas',
  'sandalias hombre': 'Hombre:Calzado:Sandalias',
  'chanclas': 'Hombre:Calzado:Sandalias',

  // NIÑOS Y BEBÉS
  'ropa bebe': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'pañalero': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'mameluco': 'Niños, Niñas y Bebés:Bebés:Ropa de Bebé',
  'zapatos bebe': 'Niños, Niñas y Bebés:Bebés:Zapatos Bebé',
  'babero': 'Niños, Niñas y Bebés:Bebés:Accesorios Bebé',
  'vestido niña': 'Niños, Niñas y Bebés:Niñas:Vestidos',
  'conjunto niña': 'Niños, Niñas y Bebés:Niñas:Conjuntos',
  'zapatos niña': 'Niños, Niñas y Bebés:Niñas:Zapatos Niña',
  'conjunto niño': 'Niños, Niñas y Bebés:Niños:Conjuntos',
  'zapatos niño': 'Niños, Niñas y Bebés:Niños:Zapatos Niño',
  'uniforme escolar': 'Niños, Niñas y Bebés:Niños:Conjuntos',

  // ==========================================================================================
  // ACCESORIOS DE MODA
  // ==========================================================================================
  'reloj casio': 'Accesorios de Moda:Relojes:Digitales',
  'reloj fossil': 'Accesorios de Moda:Relojes:Analogicos',
  'reloj rolex': 'Accesorios de Moda:Relojes:Lujo',
  'collar': 'Accesorios de Moda:Joyería:Collares',
  'cadena oro': 'Accesorios de Moda:Joyería:Collares',
  'aretes': 'Accesorios de Moda:Joyería:Aretes',
  'arracadas': 'Accesorios de Moda:Joyería:Aretes',
  'pulsera': 'Accesorios de Moda:Joyería:Pulseras',
  'anillo': 'Accesorios de Moda:Joyería:Anillos',
  'anillo compromiso': 'Accesorios de Moda:Joyería:Fina',
  'lentes de sol': 'Accesorios de Moda:Lentes:Sol',
  'ray ban': 'Accesorios de Moda:Lentes:Sol',
  'lentes oftálmicos': 'Accesorios de Moda:Lentes:Oftalmicos',
  'armazones': 'Accesorios de Moda:Lentes:Oftalmicos',
  'maleta viaje': 'Accesorios de Moda:Equipaje:Maletas',
  'mochila escolar': 'Accesorios de Moda:Equipaje:Mochilas',
  'cangurera': 'Accesorios de Moda:Equipaje:Cangureras',
  'cinturon': 'Accesorios de Moda:Varios:Cinturones',
  'gorra': 'Accesorios de Moda:Varios:Gorras',
  'sombrero': 'Accesorios de Moda:Varios:Gorras',
  'new era': 'Accesorios de Moda:Varios:Gorras',
  'bufanda': 'Accesorios de Moda:Varios:Bufandas',
  'paraguas': 'Accesorios de Moda:Varios:Paraguas',

  // ==========================================================================================
  // HOGAR, JARDÍN Y HERRAMIENTAS
  // ==========================================================================================
  
  // Muebles
  'sala': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sofa': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'sillon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sofás y Sillones',
  'mesa de centro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas de Centro',
  'mueble tv': 'Hogar, Jardín y Herramientas:Muebles y Organización:Muebles TV',
  'puff': 'Hogar, Jardín y Herramientas:Muebles y Organización:Puffs',
  'cama matrimonial': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'base cama': 'Hogar, Jardín y Herramientas:Muebles y Organización:Camas y Bases',
  'colchon': 'Hogar, Jardín y Herramientas:Muebles y Organización:Colchones',
  'colchon matrimonial': 'Hogar, Jardín y Herramientas:Muebles y Organización:Colchones',
  'cabecera': 'Hogar, Jardín y Herramientas:Muebles y Organización:Cabeceras',
  'buro': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'comoda': 'Hogar, Jardín y Herramientas:Muebles y Organización:Burós y Cómodas',
  'ropero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'closet': 'Hogar, Jardín y Herramientas:Muebles y Organización:Armarios',
  'comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Juegos de Comedor',
  'mesa comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'sillas comedor': 'Hogar, Jardín y Herramientas:Muebles y Organización:Mesas y Sillas',
  'escritorio': 'Hogar, Jardín y Herramientas:Muebles y Organización:Escritorios',
  'silla oficina': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sillas Oficina',
  'silla ergonomica': 'Hogar, Jardín y Herramientas:Muebles y Organización:Sillas Oficina',
  'archivero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',
  'librero': 'Hogar, Jardín y Herramientas:Muebles y Organización:Archiveros',

  // Cocina
  'bateria cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas y Cacerolas',
  'olla express': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Ollas Presión',
  'sarten': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'juego sartenes': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Sartenes y Woks',
  'molde pastel': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Moldes Hornear',
  'vajilla': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'platos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Juegos Vajilla',
  'vasos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'copas': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Vasos y Copas',
  'cubiertos': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cubiertos',
  'cuchillos cocina': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cuchillos Tablas',
  'tuppers': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Recipientes',
  'termo': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Termos',
  'cafetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Cafeteras',
  'tetera': 'Hogar, Jardín y Herramientas:Cocina y Mesa:Teteras',

  // Decoración
  'lampara techo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Techo',
  'lampara mesa': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Lámparas Mesa',
  'foco inteligente': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Focos',
  'tira led': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Tiras LED',
  'espejo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Espejos',
  'cuadro decorativo': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cuadros',
  'reloj pared': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Relojes Pared',
  'papel tapiz': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Vinilos',
  'cortinas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'persianas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cortinas',
  'alfombra': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'tapete': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Alfombras',
  'cojines': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Cojines',
  'velas aromaticas': 'Hogar, Jardín y Herramientas:Decoración e Iluminación:Velas',

  // Cama y Baño
  'sabanas matrimoniales': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Sábanas',
  'edredon': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'cobija': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Edredones',
  'almohada': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Almohadas',
  'toallas baño': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Toallas',
  'cortina baño': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cortinas Baño',
  'cesto ropa': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Cestos',
  'tendedero': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tendederos',
  'tabla planchar': 'Hogar, Jardín y Herramientas:Cama, Baño y Limpieza:Tablas Planchar',

  // Jardín
  'sala jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Salas Exterior',
  'hamaca': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Hamacas',
  'sombrilla jardin': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Sombrillas',
  'asador': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Asadores Carbón',
  'maceta': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Macetas',
  'plantas artificiales': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Plantas',
  'manguera': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Riego',
  'podadora': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Cortadoras',
  'desbrozadora': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Desbrozadoras',
  'alberca inflable': 'Hogar, Jardín y Herramientas:Jardín y Aire Libre:Albercas',

  // Herramientas
  'taladro': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'rotomartillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Taladros',
  'esmeriladora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Esmeriladoras',
  'sierra circular': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Sierras',
  'caladora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Sierras',
  'lijadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Lijadoras',
  'soldadora': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Soldadoras',
  'compresor aire': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Compresores',
  'set herramientas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Kits Herramientas',
  'desarmadores': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Desarmadores',
  'martillo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Martillos',
  'pinzas': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Alicates',
  'flexometro': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Medición',
  'tornillos': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Tornillos',
  'pegamento': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cinta aislar': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Pegamentos',
  'cerradura': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Cerraduras',
  'llave lavabo': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Grifería',
  'regadera': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Regaderas',
  'bomba agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Bombas Agua',
  'boiler': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'calentador agua': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Calentadores',
  'extension electrica': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'multicontacto': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Extensiones',
  'apagador': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'enchufe': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Interruptores',
  'zapatos seguridad': 'Hogar, Jardín y Herramientas:Herramientas y Mejoras:Zapatos Seguridad',

  // ==========================================================================================
  // BELLEZA Y SALUD
  // ==========================================================================================
  'limpiador facial': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'cerave': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  'agua micelar': 'Belleza y Salud:Cuidado de la Piel:Limpiadores',
  // Note: Add more Beauty if subcategories are known. 
  // Assuming standard ones based on "Limpiadores".
  
  // Generic Fallbacks
  'mujer': 'Mujer:Ropa:Blusas y Tops', // Weak fallback
  'hombre': 'Hombre:Ropa:Playeras y Polos', // Weak fallback
};
